Fix for "Route not found" issue in custom controllers using pagerfanta
sulu/sulu pull request #3473
Opened 2017-08-09 14:42 UTC by wimvds

| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | 
| Related issues/PRs | 
| License | MIT
| Documentation PR |

#### What's in this PR?

A basic route caching implementation to make getRouteByName work.

#### Why?

While integrating (already existing) custom controllers that used pagerfanta for paging data, we always got a "Route not found" exception. The root cause seemed to be that the getRouteByName function was not defined in the ContentRouteProvider. This PR just caches the route collection for the current request, so the route can be found again when the pagerfanta widget tries to generate it (with paging parameters added).

2017-08-10 06:55 UTC, wachterjohannes approved these changes
LGTM and this specific usecase seems to work also for me. but I am not 100% sure if this is a good idea, because that solves only a quite specific problem.

Maybe that could be a part of solving the problem of generating routes by name. @danrot @chirimoya what do you think? It would be also OK for me to merge this as it is.

2017-08-10 09:25 UTC, wimvds commented
I'm fully aware that it only fixes this specific use case (ie. anything that uses the route of the current request) and we could also override the provider in our own projects for now. But I think this could help a lot of users that are integrating existing code. No hard feelings if it doesn't get merged though. Still loving Sulu :+1:.

BTW If you were to decide to merge it, would it be ok if I add the same fix to the Sulu\Component\CustomUrl\Routing\CustomUrlRouteProvider as well?

2017-08-10 11:01 UTC, wachterjohannes commented
@wimvds if we merge it, it would be no problem to add it to all places we need it :) one thing we talked internal today is that we should add a comment to the code why we have added this and which usecase will be fixed by this code. Would you do that?

2017-08-10 11:05 UTC, wimvds commented
Sure, I'll do it later today or tomorrow.

2017-08-11 06:47 UTC, danrot approved these changes
For me it is also ok to merge. Better support a single use case than no usecase at all.

2017-08-14 09:42 UTC, wachterjohannes approved these changes
@danrot can be merged in my opinion

2017-08-17 09:27 UTC, wimvds commented
I noticed that there's still an issue with this : even though it works on the website, the preview in the back-end does not work. I'll try to find out why.

2017-08-17 09:50 UTC, wachterjohannes commented
@wimvds will you fix this preview bug also?

2017-08-17 10:40 UTC, wimvds commented
I'm looking into it. Will keep you updated.

2018-08-27 09:50 UTC, wimvds commented
Nope, I kind of lost track of this issue (we did the easy "fix" and decided to not show the pager on previews). Will have a look at it today, IIRC I was stuck with the routing in the preview kernel.

2018-08-28 09:37 UTC, wimvds commented
Ran into dependency hell yesterday when trying to upgrade the project we had the issue with (it uses Sylius as well ...). So I decided to create a dummy project (https://github.com/wimvds/pager-sulu-demo) to find a better way to resolve the issue.

2018-08-28 14:51 UTC, wimvds commented
The root cause of the issue seems to be that the ```sulu_route.routing.router``` is not added in the preview kernel. Trying to figure out why.

2018-09-05 15:26 UTC, wimvds commented
Ok, the root cause seemed to be that the Symfony routing is completely bypassed in the PreviewRenderer. This results in no _route being defined in the request info, and thus causes the "None of the chained routers were able to generate route: Route '' not found, Route 'Symfony\Cmf\Component\Routing\ProviderBasedGenerator' not found" exception. 

So I added a _route in the getByEntity result of the PageRouteDefaultsProvider and added a (dirty) hack to the PreviewRenderer to inject the route (with the actual path of the content).

2018-09-20 10:31 UTC, danrot requested changes
There is still a CI error... Can you also try to rebase? I guess that the reason for the circle ci error.
@wachterjohannes Can you also have another look?

2018-09-20 10:31 UTC, danrot commented on src/Sulu/Component/CustomUrl/Routing/CustomUrlRouteProvider.php
> +    public function setRouteCollection(RouteCollection $collection)
I don't think it is a good idea to introduce this method, if you only need it for tests... Then I would even prefer to set it via reflections in the test. If we introduce this method people might start using it for whatever reason...

2018-09-20 10:31 UTC, danrot commented on src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php
> +    public function setRouteCollection(RouteCollection $collection)
Same as below, would even prefer reflections in the test if this is the only reason.

2018-09-24 08:13 UTC, wimvds commented
Done. Should I also squash the commits or leave them as is?

2018-09-24 09:08 UTC, danrot approved these changes

2020-01-20 16:05 UTC, danrot commented
@wimvds I am really sorry, seem to have lost track of this PR... Is this still something you want to get merged?

2021-02-04 09:57 UTC, nnatter commented
There are a lot of merge conflicts and the last commit on this was in 2017, therefore I am going to close this. Feel free to open a new PR if this is still a problem - thanks a lot for your time!

2021-02-04 09:57 UTC, closed without merging