Add sticky ckeditor toolbar
sulu/sulu pull request #5129
Opened 2020-03-23 19:58 UTC by alexander-schranz

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes -
| Related issues/PRs | -
| License | MIT
| Documentation PR | -

#### What's in this PR?

Make the ckeditor toolbar sticky.

#### Why?

I personally think the max-height is annoying because there is never a nice UX when having 2 scrollbars in a view. I would make the text editor grow and make the toolbar sticky at current state.

#### To Do

- [ ] Create a documentation PR
- [ ] Add breaking changes to UPGRADE.md

2022-06-30 22:36 UTC, alexander-schranz commented
Maybe we can after #6676 implemented this avoid duplicated scrollbars and having nice sticky ckeditor toolbar. This would be a great UI improvements specially for articles with a lot of texts inside the editor.

2022-07-04 21:25 UTC, alexander-schranz commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/FormOverlay/formOverlay.scss
> -    position: relative;
The position relative and overflow hidden was introduced in with the snackbar component in https://github.com/sulu/sulu/pull/4717

But in the same pull request the snackbar was moved from content part of the overlay to the main part and so the change itself was not required and so it is obsolete. And as written in the comment the overflow hidden makes problems here in comby with position relative.

2022-07-07 11:24 UTC, luca-rath requested changes
Two things:

1. An old bug is back now

<img width="1840" alt="image" src="https://user-images.githubusercontent.com/5758674/177762323-88eafcce-e357-4099-8570-afedb5781ca8.png">

2. The table has a higher z-index than the toolbar

<img width="1840" alt="image" src="https://user-images.githubusercontent.com/5758674/177761921-2050efd8-e51e-416d-90d1-6192d6199baf.png">

2022-07-07 14:18 UTC, alexander-schranz commented
Good that you are reviewing this and knowing all this ckeditor quirks 😄

2022-07-07 15:22 UTC, luca-rath approved these changes

2022-07-07 15:23 UTC, merged