Add time to input field of datetime filter-type
sulu/sulu pull request #5476
Opened 2020-09-01 06:15 UTC by wachterjohannes

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | none
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR add the time to the datetime filter type input.

#### Why?

im my opinion should a datetime filter type be able to filter by "DateTIME".

#### Example Usage

~~~xml
<property name="created" translation="sulu_admin.created" type="datetime">
    <field-name>created</field-name>
    <entity-name>App\Entity\MyEntity</entity-name>

    <filter type="datetime"/>
</property>
~~~

#### BC Breaks/Deprecations

The filter type does now handle datetime.

#### To Do

- [ ] Add breaking changes to UPGRADE.md

2020-09-01 06:16 UTC, wachterjohannes commented
@chirimoya @alexander-schranz what do you think? can we change that? 

@danrot thinks we cannot change the default format for this filter type

2020-09-07 07:44 UTC, danrot requested changes

2020-09-07 11:50 UTC, wachterjohannes commented on src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/tests/registries/resourceRouteRegistry.test.js
> +        .toEqual('get_snippet?value=2013-12-24 00:00');
yes :) not found any issues with that - the browsers will escape them to `+`

2020-09-08 06:37 UTC, wachterjohannes commented
@danrot fixed

2020-09-09 08:32 UTC, danrot approved these changes

2020-09-09 08:33 UTC, merged