Add updating of exist anonymous roles
sulu/sulu pull request #5504
Opened 2020-09-21 14:56 UTC by alexander-schranz

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #5499
| Related issues/PRs | 
| License | MIT
| Documentation PR | sulu/sulu-docs#prnum

#### What's in this PR?

Add updating of exist anonymous roles.

#### Why?

As the content manager can not add permission for anonymous user a new added webspace need to add permission over the `sulu:security:init` command else the anonymous user will not have access to it.

#### Example Usage

1. `cp sulu-blog.xml sulu-blog2.xml
2. Change `<key>` to `sulu-blog2`
3. `bin/console sulu:security:init`

Exist anonymous role for same system should be updated and anonymous role should know have access to the new webspace.

2020-09-24 13:55 UTC, danrot requested changes
Just a minor change in order to be consistent. And I think we should also write tests for commands... Especially this one contains some logic, and they break so easily.

2020-09-24 13:55 UTC, danrot commented on src/Sulu/Bundle/SecurityBundle/Command/InitCommand.php
> +            $existSecurityContexts = [];
`$existingSecurityContexts`

2020-10-01 13:21 UTC, danrot commented
@alexander-schranz I would still add a test for that command... There is already quite some logic involved, and it is not tested at all :confused:

2020-10-28 08:39 UTC, alexander-schranz commented
@danrot Test added!

2020-10-28 12:02 UTC, merged