Add request parameters to SingleSelection auto_complete
sulu/sulu pull request #5506
Opened 2020-09-23 13:52 UTC by Prokyonn

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #issuenum
| Related issues/PRs | #issuenum
| License | MIT
| Documentation PR | sulu/sulu-docs#prnum

#### What's in this PR?

Adds the `request_parameters` to the options of the `SingleAutoComplete` component.

#### Why?

The same functionality was already implemented for the multi-selection types.

2020-09-24 08:54 UTC, danrot requested changes
Code looks good, but there should also be a test :slightly_smiling_face:

2020-09-24 22:35 UTC, Prokyonn commented
> Code looks good, but there should also be a test 🙂

@danrot added the missing test

2020-09-25 06:38 UTC, danrot requested changes

2020-09-25 06:38 UTC, danrot commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelection.test.js
> +
Can you please also add a test that adds options via the `requestOptions` and `dataPathToAutoComplete`? Want to make sure that the combination also works properly (including how it resolves conflicts when both write to the same parameter, not that this accidentally changes in the future).

2020-09-25 08:29 UTC, danrot approved these changes

2020-09-25 08:29 UTC, merged