Fix image_map example template
sulu/sulu pull request #5564
Opened 2020-10-22 12:29 UTC by luca-rath

| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #issuenum
| Related issues/PRs | #issuenum
| License | MIT
| Documentation PR | sulu/sulu-docs#prnum

#### What's in this PR?

Fixes image_map example template

#### Why?

If no image set in admin, an error is thrown in twig.

2020-10-22 12:30 UTC, luca-rath commented
@danrot The `media_selection`'s empty value isn't `null` either, it's an empty array

2020-10-22 12:41 UTC, alexander-schranz commented
@luca-rath its not about the `media_selection` its about the `single_media_selection` which is null if the image is not set. So this should be the case for the `image_map`, else developers will run always in the same error as you did in the example. 

See the SingleMediaSelection Content Type here: https://github.com/sulu/sulu/blob/aaa1273abefcd3016243766b0199729097dd074b/src/Sulu/Bundle/MediaBundle/Content/Types/SingleMediaSelection.php#L59-L61

2020-10-22 12:43 UTC, alexander-schranz requested changes

2020-10-22 12:43 UTC, alexander-schranz commented on templates/pages/example.html.twig
> -    {% if content.image_map %}
This is correct and should work.

2020-10-23 08:47 UTC, danrot commented
A test is missing.

2020-10-23 08:48 UTC, danrot commented on src/Sulu/Bundle/MediaBundle/Content/Types/ImageMapContentType.php
> +        if (!($data['image'] ?? null)) {
Doesn't `!isset($data['image'])` work as well? This line looks a bit confusing and unusual to me.

2020-10-23 11:56 UTC, danrot commented
The CircleCI build is currently also failing on master and this PR is not changing an JS at all... So I am going to merge that as soon as the other tests are passing.

2020-10-23 11:56 UTC, danrot approved these changes

2020-10-23 12:13 UTC, merged