Fixed deprecation messages for Doctrine\Common\Inflector\Inflector
sulu/sulu pull request #5737
Opened 2021-01-08 17:28 UTC by bramtervoort

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no 
| Fixed tickets |  - 
| Related issues/PRs |   - 
| License | MIT
| Documentation PR | -

#### What's in this PR?

Fixed deprecation messages for Doctrine\Common\Inflector\Inflector these calls now get the new Inflecto api

#### Why?

This should make future updates a little easier.

#### To Do

- [ ] update composer.json "doctrine/inflector": "^1.4 || ^2.0",

2021-01-09 16:03 UTC, alexander-schranz commented
@bramtervoort Thx for the PR. Can you target the `2.1` branch for this change? And changing the `composer.json` is fine. We need here `^1.4.1 || ^2.0.1` (we can so remove the conflicts to 1.4.0 and 2.0.0 as they are not longer in the range).
This is no breaking change as we have a requirement to `handcraftedinthealps/rest-routing-bundle` which defines min version of `doctrine/inflector` to `1.4`.

2021-01-10 16:51 UTC, bramtervoort commented
Thank you. I rebased it. if there is anything else needed i'd be haopy to do that.

2021-01-11 09:42 UTC, alexander-schranz requested changes
Some little change requests. Else it looks fine from my side.

2021-01-11 09:42 UTC, alexander-schranz commented on src/Sulu/Bundle/CoreBundle/Entity/ApiEntity.php
> +            $inflector = InflectorFactory::create()->build();
Would remove this comment does more confuse me as it helps 🙈 

```suggestion
            $inflector = InflectorFactory::create()->build();
```

2021-01-11 09:42 UTC, alexander-schranz commented on src/Sulu/Component/Content/Metadata/Factory/StructureMetadataFactory.php
> +     * @var \Doctrine\Inflector\Inflector
add here `use \Doctrine\Inflector\Inflector;` for this:

```suggestion
     * @var Inflector
```

2021-01-11 09:42 UTC, alexander-schranz commented on src/Sulu/Component/DocumentManager/Subscriber/Behavior/Path/AliasFilingSubscriber.php
> +     * @var \Doctrine\Inflector\Inflector
same as above, add here `use \Doctrine\Inflector\Inflector;` for this:

```suggestion
     * @var Inflector
```

2021-01-11 11:21 UTC, bramtervoort commented
Just applied the suggestions. Github does make that very easy. Curious if this work correctly with the tests since I did not verify the php cs of this.

2021-01-11 11:44 UTC, alexander-schranz approved these changes

2021-01-11 11:48 UTC, alexander-schranz requested changes
@bramtervoort you can also just edit the files I just write the suggestion to maybe make it easier for you but if manual change it does work better for you use that. Currently I think the use statements are missing so the IDE would fail to find the Inflector class.

2021-01-11 11:48 UTC, alexander-schranz commented on src/Sulu/Component/Content/Metadata/Factory/StructureMetadataFactory.php
> +     * @var Inflector
Looks for me like the `use` statement is missing here for this class

2021-01-11 11:48 UTC, alexander-schranz commented on src/Sulu/Component/DocumentManager/Subscriber/Behavior/Path/AliasFilingSubscriber.php
> +     * @var Inflector
Looks for me like the `use` statement is missing here for this class

2021-01-11 15:15 UTC, bramtervoort commented
yes it does work better in the editor. Thank you. i updated the use statements

2021-01-11 15:27 UTC, alexander-schranz approved these changes

2021-01-11 20:40 UTC, merged

2021-01-11 20:40 UTC, alexander-schranz commented
@bramtervoort Thank your for upgrading this! 🚀