Move blocked_file_types configuration
sulu/sulu pull request #5780
Opened 2021-01-28 14:12 UTC by luca-rath

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | yes
| Fixed tickets | -
| Related issues/PRs | -
| License | MIT
| Documentation PR | -

#### What's in this PR?

Move configuration `sulu_media.format_manager.blocked_file_types` to `sulu_media.upload.blocked_file_types`

2021-01-28 14:27 UTC, alexander-schranz requested changes
We shoudl also create a test in the `SuluMediaExtensionTest` to be sure that the implemented behaviour works.

2021-01-28 14:27 UTC, alexander-schranz commented on src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
> +            $blockedFileTypes = $config['format_manager']['blocked_file_types'];
there is also a parameter set with `sulu_media.media.blocked_file_types` which should also contain the new value. Not sure why not this parameter was use in the service definition 🙈.

2021-01-28 15:02 UTC, alexander-schranz approved these changes

2021-01-28 15:03 UTC, alexander-schranz commented
Would be nice if we add a `Configuration` section in the [MediaBundle Documentation](https://docs.sulu.io/en/2.2/bundles/media/index.html).

2021-02-03 13:52 UTC, nnatter commented
Looks good. Would be nice to add a `Configuration` section to the docs (See: this:https://docs.sulu.io/en/2.2/bundles/preview/index.html#configuration)

2021-02-03 13:54 UTC, luca-rath commented
Already on it 🙂

2021-02-03 16:19 UTC, merged