* PHP 8.x Fix deprecation notices for optional function parameters declared before required parameter.
sulu/sulu pull request #5783
Opened 2021-01-31 17:29 UTC by StaffNowa

…clared before required parameter.

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | yes
| BC breaks? | no
| Deprecations? | yes
| Fixed tickets |
| Related issues/PRs | 
| License | MIT
| Documentation PR | sulu/sulu-docs# 

#### What's in this PR?

PHP Deprecated:  Required parameter $roleRepository follows optional parameter $descendantProviders in /home/domain/domains/domain_name.com/vendor/sulu/sulu/src/Sulu/Component/Security/Authorization/AccessControl/AccessControlManager.php on line 61

#### Why?

Fix deprecation notices for optional function parameters declared before required parameter.

2021-02-01 10:51 UTC, alexander-schranz requested changes
Thx for the fix. We will provide PHP 8 support for 2.1.x branch. Can you adjust the change request and rebasse your branch to 2.1?

2021-02-01 10:51 UTC, alexander-schranz commented on src/Sulu/Component/Security/Authorization/AccessControl/AccessControlManager.php
> +        iterable $descendantProviders = []
we should not swap any parameter in the constructor. In this case I would just remove the `= []` as it doe snot make any sense

2021-02-01 10:51 UTC, alexander-schranz commented on src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
> +            <argument type="tagged_iterator" tag="sulu_security.access_control_descendant_provider"/>
we should not swap this parameters

2021-02-01 19:57 UTC, closed without merging

2021-02-01 20:05 UTC, StaffNowa commented on src/Sulu/Component/Security/Authorization/AccessControl/AccessControlManager.php
> +        iterable $descendantProviders = []
2.1.x not have these changes at all https://github.com/StaffNowa/sulu/blob/release/2.1/src/Sulu/Component/Security/Authorization/AccessControl/AccessControlManager.php

2021-02-02 18:01 UTC, StaffNowa commented
something broken in this part https://github.com/sulu/sulu/pull/5789