Make options of UploadToolbarAction consistent to other parts of the system
sulu/sulu pull request #5800
Opened 2021-02-05 14:25 UTC by nnatter

We use `snake_case` for the keys of the options of all other toolbar actions.

2021-02-05 14:25 UTC, nnatter commented on src/Sulu/Bundle/AdminBundle/Resources/js/views/List/toolbarActions/UploadToolbarAction.js
> +    @computed get errorCodeMessages(): $ReadOnly<Object> {
this makes the naming consistent with a similar option introduced in https://github.com/sulu/sulu/pull/5799

2021-02-09 18:06 UTC, alexander-schranz requested changes

2021-02-09 18:06 UTC, alexander-schranz commented on src/Sulu/Bundle/AdminBundle/Resources/js/views/List/toolbarActions/UploadToolbarAction.js
> +                router_attrbites_to_request: routerAttributesToRequest = {},
Looks like a typoe: 

```suggestion
                router_attributes_to_request: routerAttributesToRequest = {},
```

2021-02-09 18:06 UTC, alexander-schranz commented on src/Sulu/Bundle/AdminBundle/Resources/js/views/List/toolbarActions/UploadToolbarAction.js
> +            throw new Error('The "router_attrbites_to_request" option must be an object!');
Same as above:

```suggestion
            throw new Error('The "router_attributes_to_request" option must be an object!');
```

2021-02-11 16:47 UTC, alexander-schranz approved these changes

2021-02-11 16:49 UTC, alexander-schranz commented
Is okay from my side @luca-rath do you want to have also a look at this?

2021-02-12 09:24 UTC, luca-rath approved these changes

2021-02-12 09:24 UTC, merged