Display title of internal link instead of link destination in webspace overview
sulu/sulu pull request #5878
Opened 2021-03-12 14:02 UTC by nnatter

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | yes
| Fixed tickets | fixes #3721, fixes #3877
| License | MIT

#### What's in this PR?

This PR adjusts the `ContentRepository` service to return the title of the source page instead of the title of the destination
page for internal links. This affects the title that is displayed for internal links in the webspace overview.

#### Why?

This makes the displayed title consistent to the title returned by the `sulu_navigation_*` functions. Furthermore, it makes the behaviour of the `ContentRepository` consistent to the `ContentMapper`.

2021-03-12 15:55 UTC, alexander-schranz requested changes

2021-03-12 15:55 UTC, alexander-schranz commented on src/Sulu/Component/Content/Repository/ContentRepository.php
> +        $sourceNodeValueProperties = array_merge(['title'], self::$nonFallbackProperties);
`array_merge` should only be used when merging array together. If we just want to add something to an array it is more efficient to use the `[]` operator:

```suggestion
        $sourceNodeValueProperties = self::$nonFallbackProperties;
        $sourceNodeValueProperties[] = 'title';
```

You can see the difference when running:

```bash
php -r '$startTime = microtime(true);

              $array = [];

              for ($i = 0; $i <= 10000; ++$i) {
                  $array = array_merge([\'title\'], $array);
              }

              $endTime = microtime(true);

              var_dump($endTime - $startTime);'

# float(0.34501719474792)
```

vs:

```bash
php -r '
              $startTime = microtime(true);

              $array = [];

              for ($i = 0; $i <= 10000; ++$i) {
                  $array[] = \'title\';
              }

              $endTime = microtime(true);

              var_dump($endTime - $startTime);'
              
# float(0.00098204612731934)
```

Using in this benchmark 100000 will make the array_merge a lot slower.

Maybe not so relevant in this case but I would always go the `[]` way when its possible and we don't need to `merge` keys together.

2021-03-12 15:58 UTC, alexander-schranz requested changes
A change request which can be discussed, some tests are failing and I didn't yet test it locally which effects it could have on internal_links, smart content, navigation and breadcrumb.

2021-03-15 13:51 UTC, nnatter commented
@alexander-schranz Tests should pass now 🙂 
As far as i see, this should not change anything for `smart_content`, `navigation` and `breadcrumb` because they use the `ContentQueryExecuter` which uses the `ContentMapper`. 

The PR adjusts the `ContentRepository` which is used by the `PageLinkProvider`, `PagesSitemapProvider`, `CustomUrlRepository` and `PageController`

2021-03-15 13:53 UTC, alexander-schranz approved these changes

2021-03-15 13:56 UTC, merged