WIP: Dispatch domain events in CategoryBundle
sulu/sulu pull request #5900
Opened 2021-03-26 13:47 UTC by nnatter

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | yes
| BC breaks? | no
| Deprecations? | no
| Related issues/PRs | builds upon #5840
| License | MIT

#### What's in this PR?

This PR adjusts the `CategoryManager` to dispatch domain events.

2021-03-26 13:48 UTC, nnatter commented on src/Sulu/Bundle/CategoryBundle/Domain/Event/CategoryCreatedEvent.php
> +        return 'categories';
define a constant for this

2021-03-26 14:00 UTC, alexander-schranz requested changes

2021-03-26 14:00 UTC, alexander-schranz commented on src/Sulu/Bundle/CategoryBundle/Domain/Event/CategoryCreatedEvent.php
> +        return $this->category->findTranslationByLocale($this->locale)->getTranslation();
`$this->category->findTranslationByLocale($this->locale)` could return `null`

2021-03-26 14:00 UTC, alexander-schranz commented on src/Sulu/Bundle/CategoryBundle/Domain/Event/CategoryMovedEvent.php
> +        return $this->category->findTranslationByLocale($this->category->getDefaultLocale())->getTranslation();
same above the `findTranslationByLocale` can return null would more be a race condition  but maybe we should still not fail if it happens

2021-03-31 14:40 UTC, nnatter commented on src/Sulu/Bundle/CategoryBundle/Domain/Event/CategoryMovedEvent.php
> +            'newParentId' => $this->category->getParent()->getId(),
i suspect that `$this->category->getParent()` could return null, but not sure about it

2021-03-31 14:43 UTC, alexander-schranz commented on src/Sulu/Bundle/CategoryBundle/Category/CategoryManager.php
> +        $previousParentId = $category->getParent()->getId();
@nnatter think this could also be `null` when it is a root Category moved into a child

2021-04-13 09:55 UTC, alexander-schranz approved these changes

2021-04-14 07:52 UTC, wachterjohannes approved these changes

2021-04-14 07:52 UTC, merged