Referencing controllers with a single colon is deprecated
sulu/sulu pull request #5919
Opened 2021-04-05 19:21 UTC by StaffNowa

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | yes
| License | MIT

#### What's in this PR?
symfony/http-kernel 5.1 return deprecation warning

#### Why?

Change : to ::

2021-04-06 12:03 UTC, alexander-schranz requested changes
@StaffNowa thx for the pull request can you rebase then the phpstan error should be gone.

2021-04-06 12:03 UTC, alexander-schranz commented on src/Sulu/Bundle/AdminBundle/Resources/config/routing.yml
> +    defaults: { _controller: SuluAdminBundle::Security:reset }
This route looks strange. I also don' think this controller does exist, so maybe the whole route definition can be removed?

2021-04-06 13:08 UTC, StaffNowa commented on src/Sulu/Bundle/AdminBundle/Resources/config/routing.yml
> +    defaults: { _controller: SuluAdminBundle::Security:reset }
Possible we need to have 

```
defaults: { _controller: SuluAdminBundle::Security::reset }
```

not this one

```
defaults: { _controller: SuluAdminBundle:Security:reset }
```

2021-04-06 13:13 UTC, alexander-schranz commented on src/Sulu/Bundle/AdminBundle/Resources/config/routing.yml
> +    defaults: { _controller: SuluAdminBundle::Security:reset }
The controller does not longer exist since sulu 2.x so this route can be removed as it never did anything in 2.x.

2021-04-06 13:22 UTC, StaffNowa commented on src/Sulu/Bundle/AdminBundle/Resources/config/routing.yml
> +    defaults: { _controller: SuluAdminBundle::Security:reset }
This one in Sulu 2.1 I found :)

2021-04-06 13:26 UTC, alexander-schranz commented on src/Sulu/Bundle/AdminBundle/Resources/config/routing.yml
> +    defaults: { _controller: SuluAdminBundle::Security:reset }
What you mean you found? In any 2.x version there does the SecurityController not longer exist see: 

 - [https://github.com/sulu/sulu/tree/2.1/src/Sulu/Bundle/AdminBundle/Controller](https://github.com/sulu/sulu/tree/2.1/src/Sulu/Bundle/AdminBundle/Controller)
 - [https://github.com/sulu/sulu/tree/2.2/src/Sulu/Bundle/AdminBundle/Controller](https://github.com/sulu/sulu/tree/2.2/src/Sulu/Bundle/AdminBundle/Controller)
 - [https://github.com/sulu/sulu/tree/2.x/src/Sulu/Bundle/AdminBundle/Controller](https://github.com/sulu/sulu/tree/2.x/src/Sulu/Bundle/AdminBundle/Controller)
 
 only in [1.6](https://github.com/sulu/sulu/tree/1.6/src/Sulu/Bundle/AdminBundle/Controller) this did exist. So this route can safely be removed as it currently ends in a 500 error when called e.g.: [http://sulu.localhost/admin/reset/test](http://sulu.localhost/admin/reset/test).

2021-04-06 18:03 UTC, StaffNowa commented on src/Sulu/Bundle/AdminBundle/Resources/config/routing.yml
> +    defaults: { _controller: SuluAdminBundle::Security:reset }
You are right. We do not have this controller at all

2021-04-07 15:14 UTC, nnatter approved these changes
Looks good to me - thanks a lot! 

The failing pipeline is cause by a new version of the `friendsofphp/php-cs-fixer` package and not related to this PR.

2021-04-07 15:31 UTC, merged

2021-04-07 15:32 UTC, alexander-schranz approved these changes