Fix deprecated uksort implementation
sulu/sulu pull request #5923
Opened 2021-04-06 19:28 UTC by plozmun

| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | -
| Related issues/PRs | -
| License | MIT
| Documentation PR | -

#### What's in this PR?

With PHP8 there is a deprecation warning with this function. Since PHP7 is deprecated to return bool in the callback. It should return a int

2021-04-06 20:13 UTC, plozmun commented
Php Cs Fixer failures seems to be related to this https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5571/files with a new relase

2021-04-07 15:16 UTC, nnatter approved these changes
Thank you! 

The failing pipeline is cause by a new version of the `friendsofphp/php-cs-fixer` package and not related to this PR.

2021-04-07 15:48 UTC, alexander-schranz requested changes
Think this should target the `2.1` branch if this is deprecated in php. Can you rebase this to `2.1`?

2021-04-07 15:59 UTC, plozmun commented
> Think this should target the `2.1` branch if this is deprecated in php this way. Can you rebase this to `2.1`?
> 
> ```
> git rebase --interactive --onto origin/2.1 origin/2.x
> ```

Done!

2021-04-07 16:08 UTC, alexander-schranz commented
@plozmun Thank you 👍

2021-04-07 16:08 UTC, alexander-schranz approved these changes

2021-04-07 16:53 UTC, merged