Add PropertyMetadataMapper for number field type
sulu/sulu pull request #6310
Opened 2021-10-21 08:46 UTC by luca-rath

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | yes
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | -
| Related issues/PRs | -
| License | MIT
| Documentation PR | sulu/sulu-docs#684

#### What's in this PR?

Add PropertyMetadataMapper for number field type

#### Why?

This enables validation of `min`, `max` and `multiple_of` params of `number` field type.

#### Example Usage

```xml
<property name="number" type="number">
    <meta>
        <title lang="en">Number</title>
    </meta>

    <params>
        <param name="min" value="2"/>
        <param name="max" value="5"/>
        <param name="step" value="1"/>
        <param name="multiple_of" value="1"/>
    </params>
</property>
```

#### To Do

- [x] Create a documentation PR

2021-10-21 09:13 UTC, alexander-schranz requested changes

2021-10-21 09:13 UTC, alexander-schranz commented on src/Sulu/Component/Content/Tests/Unit/Types/NumberTest.php
> +            'type' => 'string',
when is this happening?

2021-10-21 09:13 UTC, alexander-schranz commented on src/Sulu/Component/Content/Types/Number.php
> +        $multipleOf = $this->getFloatParam($propertyMetadata, 'multiple_of');
I would not introduce a new parameter here I would reuse the `step` parameter. I would not support to have a different `step` and a different `multiple_of` parameter in the number type.

2021-10-21 09:17 UTC, luca-rath commented on src/Sulu/Component/Content/Types/Number.php
> +        $multipleOf = $this->getFloatParam($propertyMetadata, 'multiple_of');
I think it's a valid example to have `step=1` and `multiple_of=0.01` to allow numbers with two decimals (prices e.g.) but the number field should still use `1` as step

2021-10-21 09:18 UTC, luca-rath commented on src/Sulu/Component/Content/Tests/Unit/Types/NumberTest.php
> +            'type' => 'string',
You're right, this is never the case ... Will remove it

2021-10-21 09:23 UTC, alexander-schranz commented on src/Sulu/Component/Content/Types/Number.php
> +        $multipleOf = $this->getFloatParam($propertyMetadata, 'multiple_of');
I know what you mean and wanted to support with it but I personally would not do it. It can be misconfigured step lower then multiple_of, is step fallbacking or is multple_of of fallbacking, will multiple_of overwrite step when lower, many questions I think is added for a usecase which is mostly not used. And if there is just one value its just clear.
But if the others want also to add it I'm fine with it. /cc @sulu/core-team

2021-10-21 09:26 UTC, alexander-schranz commented on src/Sulu/Component/Content/Types/Number.php
> +        $multipleOf = $this->getFloatParam($propertyMetadata, 'multiple_of');
I would at current state go with `step` and wait for feedback. If this is then requested we still could add `multiple_of` but at current state I would just use the value from `step`.

2021-10-21 09:37 UTC, luca-rath commented on src/Sulu/Component/Content/Types/Number.php
> +        $multipleOf = $this->getFloatParam($propertyMetadata, 'multiple_of');
We could just throw an exception if `step` is not a multiple of `multiple_of` - then there's no fallback "magic" ... But `step` shouldn't be used for validation IMO, because if you specify `step` on a html input element, you can still type in numbers between steps, there won't be an error. And in the docs we could clearly specify that `step` is just used for the ui while `multiple_of` is used for validation

2021-10-21 10:05 UTC, alexander-schranz commented on src/Sulu/Component/Content/Types/Number.php
> +        $multipleOf = $this->getFloatParam($propertyMetadata, 'multiple_of');
I'm aware of how html is handling it but as said I would at current state not add an additional parameter for it.

2021-10-27 12:30 UTC, niklasnatter commented on src/Sulu/Component/Content/Types/Number.php
> +        $multipleOf = $this->getFloatParam($propertyMetadata, 'multiple_of');
dont have a strong opinion here - both options are okay for me

2021-12-02 13:38 UTC, alexander-schranz approved these changes

2021-12-02 13:42 UTC, alexander-schranz commented on src/Sulu/Component/Content/Types/Number.php
> +        $multipleOf = $this->getFloatParam($propertyMetadata, 'multiple_of');
/cc @chirimoya

2021-12-02 16:44 UTC, alexander-schranz commented on src/Sulu/Component/Content/Types/Number.php
> +        $multipleOf = $this->getFloatParam($propertyMetadata, 'multiple_of');
@luca-rath I did discuss it with @chirimoya and we keep step and multiple_of. So the PR is ready. Can you check the PHP Lint failings then we could also merge this.

2021-12-02 17:06 UTC, alexander-schranz approved these changes

2021-12-02 17:19 UTC, merged