fix: pass original request server parameters to target group request
sulu/sulu pull request #6406
Opened 2021-12-03 08:25 UTC by lgraubner

| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #
| Related issues/PRs | #
| License | MIT
| Documentation PR | sulu/sulu-docs#

#### What's in this PR?

This PR passes the original request server headers to the audience targeting request.

#### Why?

When using the `{host}`placeholder in the webspace configuration every request handled through `_sulu_target_group` results in a `UrlMatchNotFoundException There exists no portal for the URL "_sulu_target_group"`. As the `ForwardedUrlRequestProcessor` creates a new request without passing the original requests `host` header it fall backs to `localhost` which does not seem to work. If a specific host is set in the webspace configuration it works.

2021-12-07 06:58 UTC, wachterjohannes commented
@lgraubner i cannot reproduce your problem but it does not seem to break anything - thanks for the contribution. Can you maybe add a comment about your thoughts in the class and a testcase to the TestClass `src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Request/ForwardedUrlRequestProcessorTest.php` to ensure that nobody remove the headers from the class.

2021-12-07 07:00 UTC, wachterjohannes requested changes
see comment above

2021-12-07 07:02 UTC, wachterjohannes commented
@lgraubner OK i see my problem 🙈  i have configured the URL in the webspace. with the {host} parameter it really seems to break.

But my comment above is still valid

2021-12-14 10:40 UTC, alexander-schranz commented
As a bugfix we should target the `2.2` branch for this as I think the bug also exist there?

2021-12-22 14:33 UTC, wachterjohannes approved these changes

2021-12-22 14:58 UTC, merged