Improve dependant overlay messages
sulu/sulu pull request #6424
Opened 2021-12-14 20:36 UTC by alexander-schranz

| Q | A
| --- | ---
| Bug fix? | no 
| New feature? | no 
| BC breaks? | no 
| Deprecations? | no  
| Fixed tickets | fixes # 
| Related issues/PRs | # 
| License | MIT
| Documentation PR | sulu/sulu-docs# 

#### What's in this PR?

Improve dependant overlay messages.

#### Why?

The exist dependant messages are very unspecific and can confuse Users so we go with a more specific message for the overlay and make it possible to control it from PHP instead of hardcode it in the JS.

2021-12-14 23:44 UTC, alexander-schranz commented on src/Sulu/Bundle/MediaBundle/Resources/translations/admin.de.json
> +    "sulu_media.delete_collection_warning_title": "{1}Eine zusätzliche abhängige Kollektion oder Medium löschen|]1,Inf[%count% zusätzliche abhängige Kollektionen oder Medien löschen",
This is a little bit to long as "title" what would you suggest here @chirimoya

2021-12-15 13:42 UTC, chirimoya requested changes

2021-12-15 13:42 UTC, chirimoya commented on src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
> +    "sulu_admin.delete_dependants_warning_title": "{1}Ein zusätzliche abhängiges Element löschen|]1,Inf[%count% zusätzliche abhängige Elemente löschen",
```suggestion
    "sulu_admin.delete_dependants_warning_title": "{1}Ein abhängiges Element löschen?|]1,Inf[%count% abhängige Elemente löschen?",
```

2021-12-15 13:42 UTC, chirimoya commented on src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
> +    "sulu_admin.delete_dependants_warning": "{1}Sind Sie sich sicher, dass Sie ein zusätzlich abhängiges Element ebenfalls löschen möchten?|]1,Inf[Sind Sie sich sicher, dass Sie %count% abhängige Ele
```suggestion
    "sulu_admin.delete_dependants_warning": "{1}Sind Sie sich sicher, dass Sie zusätzlich ein abhängiges Element löschen möchten?|]1,Inf[Sind Sie sich sicher, dass Sie zusätzlich %count% abhängige Elemente löschen möchten?",
```

2021-12-15 13:42 UTC, chirimoya commented on src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
> +    "sulu_admin.delete_dependants_warning": "{1}Are you sure, that you want to delete one additional dependant element?|]1,Inf[Are you sure, that you want to delete %count% additional dependant eleme
```suggestion
    "sulu_admin.delete_dependants_warning": "{1}Are you sure that you also want to delete one dependant element?|]1,Inf[Are you sure that you also want to delete %count% dependant elements?",
```

2021-12-15 13:42 UTC, chirimoya commented on src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
> +    "sulu_admin.delete_dependants_warning_title": "{1}Delete one additional dependant element|]1,Inf[Delete %count% additional dependant elements",
```suggestion
    "sulu_admin.delete_dependants_warning_title": "{1}Delete one dependant element?|]1,Inf[Delete %count% dependant elements?",
```

2021-12-15 13:42 UTC, chirimoya commented on src/Sulu/Bundle/CategoryBundle/Resources/translations/admin.de.json
> +    "sulu_category.delete_category_warning_title": "{1}Zusätzliche abhängige Kategorie löschen|]1,Inf[%count% zusätzliche abhängige Kategorien löschen",
```suggestion
    "sulu_category.delete_category_warning_title": "{1}Eine Unterkategorie löschen?|]1,Inf[%count% Unterkategorien löschen?",
```

2021-12-15 13:42 UTC, chirimoya commented on src/Sulu/Bundle/CategoryBundle/Resources/translations/admin.de.json
> +    "sulu_category.delete_category_warning": "{1}Sind Sie sich sicher, dass Sie eine zusätzliche abhängige Kategorie ebenfalls löschen möchten?|]1,Inf[Sind Sie sich sicher, dass Sie %count% zusätzlic
```suggestion
    "sulu_category.delete_category_warning": "{1}Sind Sie sich sicher, dass Sie zusätzlich eine Unterkategorie löschen möchten?|]1,Inf[Sind Sie sich sicher, dass Sie zusätzlich %count% Unterkategorien löschen möchten?",
```

2021-12-15 13:42 UTC, chirimoya commented on src/Sulu/Bundle/CategoryBundle/Resources/translations/admin.en.json
> +    "sulu_category.delete_category_warning_title": "{1}Delete one additional category|]1,Inf[Delete %count% additional categories",
```suggestion
    "sulu_category.delete_category_warning_title": "{1}Delete one subcategory?|]1,Inf[Delete %count% subcategories?",
```

2021-12-15 13:42 UTC, chirimoya commented on src/Sulu/Bundle/CategoryBundle/Resources/translations/admin.en.json
> +    "sulu_category.delete_category_warning": "{1}Are you sure, that you want to delete one additional category?|]1,Inf[Are you sure, that you want to delete %count% categories?",
```suggestion
    "sulu_category.delete_category_warning": "{1}Are you sure that you also want to delete one subcategory?|]1,Inf[Are you sure that you also want to delete %count% subcategories?",
```

2021-12-15 13:42 UTC, chirimoya commented on src/Sulu/Bundle/PageBundle/Resources/translations/admin.de.json
> +    "sulu_page.delete_page_warning_title": "{1}Zusätzliche abhängige Seite löschen|]1,Inf[%count% zusätzliche abhängige Seiten löschen",
```suggestion
    "sulu_page.delete_page_warning_title": "{1}Eine Unterseite löschen?|]1,Inf[%count% Unterseiten löschen?",
```

2021-12-15 13:42 UTC, chirimoya commented on src/Sulu/Bundle/PageBundle/Resources/translations/admin.de.json
> +    "sulu_page.delete_page_warning": "{1}Sind Sie sich sicher, dass Sie eine zusätzliche abhängige Seite ebenfalls löschen möchten?|]1,Inf[Sind Sie sich sicher, dass Sie %count% zusätzliche abhängige
```suggestion
    "sulu_page.delete_page_warning": "{1}Sind Sie sich sicher, dass Sie zusätzlich eine Unterseiten löschen möchten?|]1,Inf[Sind Sie sich sicher, dass Sie zusätzlich %count% Unterseiten löschen möchten?",
```

2021-12-15 13:42 UTC, chirimoya commented on src/Sulu/Bundle/PageBundle/Resources/translations/admin.en.json
> +    "sulu_page.delete_page_warning_title": "{1}Delete one additional page|]1,Inf[Delete %count% additional pages",
```suggestion
    "sulu_page.delete_page_warning_title": "{1}Delete one subpage?|]1,Inf[Delete %count% subpages?",
```

2021-12-15 13:42 UTC, chirimoya commented on src/Sulu/Bundle/PageBundle/Resources/translations/admin.en.json
> +    "sulu_page.delete_page_warning": "{1}Are you sure, that you want to delete one additional page?|]1,Inf[Are you sure, that you want to delete %count% additional pages?",
```suggestion
    "sulu_page.delete_page_warning": "{1}Are you sure that you also want to delete one subpage?|]1,Inf[Are you sure that you also want to delete %count% subpages?",
```

2021-12-15 13:42 UTC, chirimoya commented on src/Sulu/Bundle/MediaBundle/Resources/translations/admin.de.json
> +    "sulu_media.delete_collection_warning_title": "{1}Eine zusätzliche abhängige Kollektion oder Medium löschen|]1,Inf[%count% zusätzliche abhängige Kollektionen oder Medien löschen",
```suggestion
    "sulu_media.delete_collection_warning_title": "{1}Ein Unterelement löschen?|]1,Inf[%count% Unterelemente löschen?",
```

2021-12-15 13:42 UTC, chirimoya commented on src/Sulu/Bundle/MediaBundle/Resources/translations/admin.de.json
> +    "sulu_media.delete_collection_warning": "{1}Sind Sie sich sicher, dass Sie ein zusätzlich abhängige Kollektion oder Medium ebenfalls löschen möchten?|]1,Inf[Sind Sie sich sicher, dass Sie %count%
```suggestion
    "sulu_media.delete_collection_warning": "{1}Sind Sie sich sicher, dass Sie zusätzlich einen Unterordner oder ein Medium löschen möchten?|]1,Inf[Sind Sie sich sicher, dass Sie zusätzlich %count% Unterordner beziehungsweise Medien löschen möchten?",
```

2021-12-15 13:42 UTC, chirimoya commented on src/Sulu/Bundle/MediaBundle/Resources/translations/admin.en.json
> +    "sulu_media.delete_collection_warning_title": "{1}Delete one additional collection or media|]1,Inf[Delete %count% additional collection or media",
```suggestion
    "sulu_media.delete_collection_warning_title": "{1}Delete one subelement?|]1,Inf[Delete %count% subelements?",
```

2021-12-15 13:42 UTC, chirimoya commented on src/Sulu/Bundle/MediaBundle/Resources/translations/admin.en.json
> +    "sulu_media.delete_collection_warning": "{1}Are you sure, that you want to delete one additional collection or media?|]1,Inf[Are you sure, that you want to delete %count% additional collection or
```suggestion
    "sulu_media.delete_collection_warning": "{1}Are you sure that you also want to delete one subcollection or media?|]1,Inf[Are you sure that you also want to delete %count% subcollection or media?",
```

2021-12-15 16:19 UTC, merged