Dispatch PageTranslationRestoredEvent when restoring single translation only
sulu/sulu pull request #6474
Opened 2022-01-25 16:01 UTC by niklasnatter

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Related issues/PRs | #6337
| License | MIT

#### What's in this PR?

This PR adjusts the `PageTrashItemHandler` service to dispatch a `PageTranslationRestoredEvent` instead of a `PageRestoredEvent` if a single translation is restored.

#### Why?

This allows us to display a more intuitive message in the activity log. Also, we already dispatch specific events when managing translations in other places (eg. `PageTranslationCopiedEvent` and `PageTranslationRemovedEvent`).

2022-02-23 15:16 UTC, wachterjohannes requested changes
@niklasnatter is there nowhere a test which does a restore? If it would be one we should add a check there if the correct event is thrown

2022-02-23 15:20 UTC, niklasnatter commented
@wachterjohannes No, unfortunately the activites of the bundle are not tested anywhere at the moment. Should I add a test?

2022-02-23 15:21 UTC, wachterjohannes commented
@niklasnatter yes please

2022-02-24 07:03 UTC, wachterjohannes commented
@niklasnatter the tests are failing 🙈

2022-02-24 07:53 UTC, niklasnatter commented
@wachterjohannes Yes unfortunately, but the failing tests are not caused by the changes in this PR. The same tests are failing on the target branch: https://github.com/sulu/sulu/actions

2022-02-24 07:58 UTC, wachterjohannes approved these changes

2022-02-24 07:58 UTC, merged