Add password-pattern
sulu/sulu pull request #6544
Opened 2022-04-19 12:51 UTC by wachterjohannes

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | yes
| BC breaks? | yes
| Deprecations? | no
| Fixed tickets | fixes none
| Related issues/PRs | none
| License | MIT
| Documentation PR | sulu/sulu-docs#TODO

#### What's in this PR?

This PR add a pattern to validate user password.

#### Why?

The administrator should be able to set the password restrictions for the users.

#### Example Usage

* The password length must be greater than or equal to 8
* The password must contain one or more uppercase characters
* The password must contain one or more lowercase characters
* The password must contain one or more numeric values
* The password must contain one or more special characters

```yaml
sulu_security:
    password:
        pattern: '(?=^.{8,}$)(?=.*\d)(?=.*[!@#$%^&*]+)(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$'
```

#### To Do

- [ ] Create a documentation PR
- [ ] Add breaking changes to UPGRADE.md

2022-04-20 10:00 UTC, alexander-schranz commented
@wachterjohannes the example with special characters should use `[^a-zA-Z0-9]` instead of a specific list of characters `[!@#$%^&*]` example the list don't allow `?`, backticks or any other special characters.

Example: 

```
/(?=^.{8,}$)(?=.*\d)(?=.*[^a-zA-Z0-9]+)(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$/
```

2022-04-25 13:33 UTC, alexander-schranz commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/ResetPasswordForm.js
> +    @observable errorKey: string;
where is this set and used?

2022-04-25 13:34 UTC, alexander-schranz commented on src/Sulu/Bundle/SecurityBundle/DependencyInjection/Configuration.php
> +                        ->scalarNode('information_translation_key')
would call it `info` like it is `info_text` in the xml

2022-04-25 13:40 UTC, alexander-schranz requested changes
Looks like there is an unused variable. And can you rebase the branch? 

Would like if @niklasnatter could have also a quick look at the JS.

2022-04-25 13:40 UTC, alexander-schranz commented on src/Sulu/Bundle/SecurityBundle/DependencyInjection/SuluSecurityExtension.php
> +        $container->setParameter('sulu_security.password_policy.information_translation_key', $passwordPolicyEnabled ? $config['password_policy']['information_translation_key'] : null);
would go here also with `info` instead of `information`

2022-04-25 13:40 UTC, alexander-schranz commented on src/Sulu/Bundle/SecurityBundle/DependencyInjection/SuluSecurityExtension.php
> +        $container->setParameter('sulu_security.password_policy.pattern', $passwordPolicyEnabled ? $config['password_policy']['pattern'] : null);
I thought we once said there should never be 2 points in any bundle specific keys. But not sure 🤔 we should have once some discussion and create here a rule set about `keys` for parameters, services and translation keys.

2022-04-26 09:38 UTC, wachterjohannes commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/ResetPasswordForm.js
> +    @observable errorKey: string;
your right - will remove it

2022-04-27 09:55 UTC, niklasnatter commented on src/Sulu/Bundle/AdminBundle/Controller/AdminController.php
> +                'password_information_key' => $this->passwordInformationKey,
think i would use `password_info_translation_key` here too

2022-04-27 09:55 UTC, niklasnatter commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/ResetPasswordForm.js
> +    @observable error: ?string = null;
would call this `errorMessage` and directly set the translated message that is displayed

2022-04-27 09:55 UTC, niklasnatter commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/ResetPasswordForm.js
> +const ERROR_MAP = {
would directly set the translated message instead of introducing an indirection

2022-04-27 09:55 UTC, niklasnatter commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/ResetPasswordForm.js
> +            this.error = 'match';
would directly set `translate('sulu_admin.reset_password_error')`

2022-04-27 09:55 UTC, niklasnatter commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/ResetPasswordForm.js
> +            this.error = 'pattern';
would directly set `translate('sulu_admin.reset_password_pattern_error')`

2022-04-27 09:55 UTC, niklasnatter commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/ResetPasswordForm.js
> +    @computed get matchPattern(): boolean {
think i would not add a property for this but just call the `userStore.validatePassword` directly. at the moment, the validation will be executed on every keystroke

2022-05-06 09:51 UTC, niklasnatter approved these changes

2022-05-06 09:53 UTC, alexander-schranz approved these changes

2022-05-06 09:53 UTC, merged