Fix link problems
sulu/sulu pull request #6648
Opened 2022-06-14 08:00 UTC by wachterjohannes

| Q | A
| --- | ---
| Bug fix? | no yes
| New feature? | no yes
| BC breaks? | no yes
| Deprecations? | no yes 
| Fixed tickets | fixes # 
| Related issues/PRs | # 
| License | MIT
| Documentation PR | sulu/sulu-docs# 

#### What's in this PR?

#### Why?

#### Example Usage

#### To Do

- [ ] Create a documentation PR
- [ ] Add breaking changes to UPGRADE.md

2022-06-14 08:29 UTC, alexander-schranz requested changes
@niklasnatter can you have a look at the `load` handling? That should fix #6528 / #6525

2022-06-14 08:29 UTC, alexander-schranz commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js
> +                } = {},
Looks like a new feature which should be documented. Personally I would prefer that this is splitted into feature targetting 2.5 and bugfix targetting 2.4.

2022-06-14 08:29 UTC, alexander-schranz commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js
> +                excludedTypes={excludedProviderTypes}
Feels a little bit strange having both types and excludedTypes but I understand that LinkContainer has the registry and so is the only place to filter them out. So its fine for me.

2022-06-14 08:29 UTC, alexander-schranz commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/Link.js
> +    @action load = (value) => {
This is a bugfix which should target the `2.4` branch. Would also like that @niklasnatter have a look at this.

2022-06-14 08:29 UTC, alexander-schranz commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/Link.js
> +                                            style={{width: 100 / displayProperties.length + '%'}}
Why this inline styling? Also calculation by string length doesn't work with our font as it is not a monofont.

2022-06-14 08:29 UTC, alexander-schranz commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/tests/Link.test.js
> +import {ResourceRequester} from 'sulu-admin-bundle/services';
you are in sulu-admin-bundle so you should use relative path to services

2022-06-20 13:57 UTC, niklasnatter commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js
> +                throw new Error('The "schemes" schema option must be an array!');
`schemes` is misleading

2022-06-20 13:57 UTC, niklasnatter commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js
> +                throw new Error('The "schemes" schema option must contain some values!');
`schemes` is misleading

2022-06-20 13:57 UTC, niklasnatter commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js
> +                        'Every type in the "types" schemaOption must contain a string as name'
`types` is misleading

2022-06-20 13:57 UTC, niklasnatter commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js
> +                throw new Error('The "schemes" schema option must be an array!');
```suggestion
                throw new Error('The "excluded_types" schema option must be an array!');
```

2022-06-20 13:57 UTC, niklasnatter commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js
> +                throw new Error('The "schemes" schema option must contain some values!');
```suggestion
                throw new Error('The "excluded_types" schema option must contain some values!');
```

2022-06-20 13:57 UTC, niklasnatter commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js
> +            const types: Array<any> | IObservableArray<any> = unvalidatedExcludedTypes;
```suggestion
            const excludedTypes: Array<any> | IObservableArray<any> = unvalidatedExcludedTypes;
```

2022-06-20 13:57 UTC, niklasnatter commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js
> +            if (types.length === 0) {
```suggestion
            if (excludedTypes.length === 0) {
```

2022-06-20 13:57 UTC, niklasnatter commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js
> +            excludedProviderTypes = types.map((type) => {
```suggestion
            excludedProviderTypes = excludedTypes.map((type) => {
```

2022-06-20 13:57 UTC, niklasnatter commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js
> +                        'Every type in the "types" schemaOption must contain a string as name'
```suggestion
                        'Every type in the "excluded_types" schemaOption must contain a string as name'
```

2022-06-20 13:57 UTC, niklasnatter commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/Link.js
> +        const options = linkTypeRegistry.getOptions(value.provider);
i think this does not work for medias at the moment. we need to set the options here:
https://github.com/sulu/sulu/blob/2.5/src/Sulu/Bundle/MediaBundle/Resources/js/index.js#L70

2022-06-20 13:57 UTC, niklasnatter commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/Link.js
> +        if (prevProps.value !== this.props.value) {
this will compare object references. we should use the `fast-deep-equals` package like in other components:
https://github.com/sulu/sulu/blob/2.5/src/Sulu/Bundle/LocationBundle/Resources/js/containers/Location/Location.js#L53

2022-06-20 13:57 UTC, niklasnatter commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/Link.js
> +                            {this.displayPropertiesLoading && '…'}
can we display a loader too like we do for other `single_selections`?

2022-06-20 13:57 UTC, niklasnatter commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/Link.js
> +                                            style={{width: 100 / displayProperties.length + '%'}}
i think this was copied from the `SingleSelection`. probably not a perfect solutions, but it worked okay there 🙂 
https://github.com/sulu/sulu/blob/d7015e35982db332e6dc91b2567876e3c135e139/src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/SingleSelection.js#L164-L174

2022-06-20 13:57 UTC, niklasnatter commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/Link.js
> +            this.displayProperties = Object.keys(data)
saving this as an object is not needed as far as i see. i think it would be easier to understand if we call this `titleParts` (and `titleLoading`). `titleParts` can just be an array of strings

2022-06-22 12:08 UTC, wachterjohannes commented on src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js
> +                } = {},
@alexander-schranz have splitted it to an own PR https://github.com/sulu/sulu/pull/6660

2022-06-27 08:47 UTC, niklasnatter approved these changes
looks good to me 🙂

2022-06-27 08:47 UTC, merged