Adding an html_decode to the webspace name to also show special chara…
sulu/sulu pull request #6714
Opened 2022-07-19 19:03 UTC by mamazu

| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #6706
| Related issues/PRs | -
| License | MIT
| Documentation PR | -

#### What's in this PR?

This PR will fix the generated code for the webspace collection cache.

#### Why?

If you configure a name in the XML file you also want to have it be displayed the same on the website. For an example see #6706

You can't just use the raw filter because this will create an issue with the surrounding code resulting in something like this:
```php
$webspace->setName('Tim's Webspace');
```

#### Example Usage

Just like before and now you can also have apostrophies in your webspace name.

#### To Do

- [x] Create a documentation PR (not needed)
- [x] Add breaking changes to UPGRADE.md (not needed)

2022-07-19 19:20 UTC, mamazu commented
Codestyle is broken but it can't be my class since this isn't even a proper class. :D

2022-07-19 20:09 UTC, alexander-schranz commented on src/Sulu/Component/Webspace/Resources/skeleton/WebspaceCollectionClass.php.twig
> +        $webspace->setName(html_entity_decode('{{ webspace.name }}'));
We should write the properties already correctly into this cache file.

The problem here currently is the "Twig" autoescaping. Which I think we should disable and go with a "json_encode" solution here:

https://twigfiddle.com/d3hoih

https://twigfiddle.com/d3hoih

2022-07-19 20:09 UTC, alexander-schranz requested changes
Good catch. Some small comment.

2022-07-20 08:34 UTC, mamazu commented on src/Sulu/Component/Webspace/Resources/skeleton/WebspaceCollectionClass.php.twig
> +        $webspace->setName(html_entity_decode('{{ webspace.name }}'));
Yes this makes it easier. I have changed it to JSON now.

2022-07-20 08:39 UTC, alexander-schranz commented on src/Sulu/Component/Webspace/Resources/skeleton/WebspaceCollectionClass.php.twig
> +        $webspace->setName(json_decode({{ webspace.name|json_encode }}));
json_decode is not required here:

```suggestion
        $webspace->setName({{ webspace.name|json_encode|raw }});
```

2022-07-20 08:40 UTC, mamazu commented on src/Sulu/Component/Webspace/Resources/skeleton/WebspaceCollectionClass.php.twig
> +        $webspace->setName(json_decode({{ webspace.name|json_encode }}));
You're right. :D

2022-07-20 08:41 UTC, alexander-schranz commented on src/Sulu/Component/Webspace/Resources/skeleton/WebspaceCollectionClass.php.twig
> +        $webspace->setName({{ webspace.name|json_encode }});
```suggestion
        $webspace->setName({{ webspace.name|json_encode|raw }});
```

raw is required or as written in the comment autoescape false ;)

2022-07-20 08:42 UTC, alexander-schranz commented
Can you add a testcase for your case.

2022-07-20 08:47 UTC, mamazu commented
Where would be the best way to put it?

2022-07-20 18:35 UTC, mamazu commented
And what about the other code that is failing the pipeline?

2022-07-20 18:40 UTC, alexander-schranz commented
We sadly did not yet found out why the PHP 8.0 tests in 90% run into a timeout but work without problems locally. Funfact it seems always be that there is atleast one CI whatever it is which just like to go into timeout instead of running finish a job. Still there are PR where all runs without any problems.

The `Test application / PHP Lint (pull_request)` can be ignored. If it doesn't show anything related to your pull request. We mostly get new versions of phpstan or php-cs-fixer which can make the CI fail. But that is a job we are doing and contributers shoud focus on the PR itself :)

2022-07-20 18:47 UTC, alexander-schranz commented
For the test I would create a unit test for the `PhpWebspaceCollectionDumper` class.

Somewhere here: https://github.com/sulu/sulu/tree/2.4/src/Sulu/Component/Webspace/Tests/Unit/Manager

By creating a `Dumper` namespace.

You can create the given `WebspaceCollection` by creating one via:

```php
$webspaceCollection = new WebspaceCollection();
// and add then different webspace
$webspace = new Webspace();
$webspaceCollection->add(...);
```

Call the dumper then and after it you `require` the generated collection and call the getter to test if you get the correct name.

2022-07-21 17:34 UTC, alexander-schranz commented
@mamazu looks good. Can we rebase this branch to the `2.4` and set the target branch to 2.4? 

Copy & Paste rebase script:

```bash
git clone git@github.com:mamazu/sulu.git
cd sulu
git checkout webspace_name_bug

git remote add sulu git@github.com:sulu/sulu.git
git fetch sulu

git rebase -i sulu/2.5 --onto sulu/2.4
# close shown file

git push origin webspace_name_bug --force # force required in this case
```

2022-07-21 18:31 UTC, mamazu commented
Should be done.

2022-07-21 18:33 UTC, alexander-schranz commented on src/Sulu/Component/Webspace/Tests/Unit/Manager/PhpWebspaceCollectionDumperTest.php
> +        $this->assertEquals($expected, $string);
```suggestion
        $this->assertSame($expected, $string);
```

2022-07-21 18:33 UTC, alexander-schranz commented on src/Sulu/Component/Webspace/Tests/Unit/Manager/PhpWebspaceCollectionDumperTest.php
> +        $this->assertEquals($expected, $string);
```suggestion
        $this->assertSame($expected, $string);
```

2022-07-21 18:34 UTC, alexander-schranz commented
Did quickly replace the assertEquals with assertSame as we are trying to use typesafe phpunit methods where possible.

2022-07-21 18:35 UTC, mamazu commented
Yeah, old habits hardly die with the old method. :D

2022-07-21 19:02 UTC, alexander-schranz requested changes
CI seems to fail I added comments to the line failing:

2022-07-21 19:02 UTC, alexander-schranz commented on src/Sulu/Component/Webspace/Tests/Unit/Manager/PhpWebspaceCollectionDumperTest.php
> +    private PhpWebspaceCollectionDumper $webspaceDumper;
looks like php 7.2 does not like this:

```suggestion
     /**
      * @var PhpWebspaceCollectionDumper
      */
    private $webspaceDumper;
```

2022-07-21 19:02 UTC, alexander-schranz commented on src/Sulu/Component/Webspace/Tests/Unit/Manager/PhpWebspaceCollectionDumperTest.php
> +    private $webspaceCollection;
Should be:

```suggestion
    /**
     * @var ObjectProphecy<WebspaceCollection>
     */
    private $webspaceCollection;
```

ObjectProphecy need to be imported.

2022-07-21 19:02 UTC, alexander-schranz commented on src/Sulu/Component/Webspace/Tests/Unit/Manager/PhpWebspaceCollectionDumperTest.php
> +    use ProphecyTrait;
Think this is not required on the 2.4 branch / it does not exist on it. I will add it when merging it back to 2.5.

2022-07-21 19:33 UTC, mamazu commented on src/Sulu/Component/Webspace/Tests/Unit/Manager/PhpWebspaceCollectionDumperTest.php
> +    private PhpWebspaceCollectionDumper $webspaceDumper;
Good old php7.2 :D

2022-07-22 08:18 UTC, merged

2022-07-22 08:18 UTC, alexander-schranz commented
@mamazu Thank you!