Add copy-snippet button in form
sulu/sulu pull request #6859
Opened 2022-10-20 07:03 UTC by wachterjohannes

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | yes
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #6609
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR add the copy button to the snippet form

2022-10-21 06:33 UTC, wachterjohannes commented
@alexander-schranz have extracted the php-cs fixes and phpstan fixes into an own PR https://github.com/sulu/sulu/pull/6862

2022-10-27 14:48 UTC, wachterjohannes commented
@alexander-schranz ping

2022-10-28 08:48 UTC, alexander-schranz commented on src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
> +
We hav eno strict_types yet in any files.
```suggestion
```

2022-10-28 08:48 UTC, wachterjohannes commented
@alexander-schranz resolved

2022-10-28 08:49 UTC, alexander-schranz requested changes
unexpected code style changes.

2022-10-28 08:49 UTC, alexander-schranz commented on src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
> +        $defaultEnabled,
we don't have this in the sulu php-cs yet

```suggestion
        $defaultEnabled
```

2022-10-28 08:49 UTC, alexander-schranz commented on src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
> +                    ->addToolbarActions($listToolbarActions),
```suggestion
                    ->addToolbarActions($listToolbarActions)
```

2022-10-28 08:49 UTC, alexander-schranz commented on src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
> +                    ->setBackView(static::LIST_VIEW),
```suggestion
                    ->setBackView(static::LIST_VIEW)
```

2022-10-28 08:49 UTC, alexander-schranz commented on src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
> +                    ->setParent(static::ADD_FORM_VIEW),
```suggestion
                    ->setParent(static::ADD_FORM_VIEW)
```

2022-10-28 08:49 UTC, alexander-schranz commented on src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
> +                    ->setTitleProperty('title'),
```suggestion
                    ->setTitleProperty('title')
```

2022-10-28 08:49 UTC, alexander-schranz commented on src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
> +                    ->setParent(static::EDIT_FORM_VIEW),
```suggestion
                    ->setParent(static::EDIT_FORM_VIEW)
```

2022-10-28 08:49 UTC, alexander-schranz commented on src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
> +                    ->setParent(static::EDIT_FORM_VIEW),
```suggestion
                    ->setParent(static::EDIT_FORM_VIEW)
```

2022-10-28 08:49 UTC, alexander-schranz commented on src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
> +                    ->addRerenderAttribute('webspace'),
```suggestion
                    ->addRerenderAttribute('webspace')
```

2022-10-28 08:49 UTC, alexander-schranz commented on src/Sulu/Bundle/SnippetBundle/Tests/Unit/Admin/SnippetAdminTest.php
> +                    $dropdownActions,
```suggestion
                    $dropdownActions
```

2022-10-28 08:49 UTC, alexander-schranz commented on src/Sulu/Bundle/SnippetBundle/Tests/Unit/Admin/SnippetAdminTest.php
> +                    $dropdownActions,
```suggestion
                    $dropdownActions
```

2022-10-28 09:31 UTC, wachterjohannes commented
@alexander-schranz fixed

2022-10-28 09:34 UTC, alexander-schranz approved these changes

2022-10-28 09:45 UTC, merged