Add condition to StructureProvider
sulu/sulu pull request #6868
Opened 2022-10-27 14:17 UTC by thomasduenser

Necessary for the MassiveSearchBundle so that too many fields are no longer generated for blocks.

| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | yes - The search index has lesser fields now as only the necessary ones are created (and grouped).
| Deprecations? | no
| Fixed tickets | #6501 
| Related issues/PRs | https://github.com/massiveart/MassiveSearchBundle/pull/168/files
| License | MIT
| Documentation PR | -

#### What's in this PR?

This PR adds the `$condition` to the `mapProperty` method. This is necessary for the MassiveSearchBundle to validate if the field should be indexed or not (when using the same property names across multiple block types).

#### Why?

To fix the ElasticSearch error:

```
Limit of total fields [1000] has been exceeded
```

2022-10-27 14:34 UTC, wachterjohannes approved these changes
@alexander-schranz WDYT?

2022-10-28 08:25 UTC, wachterjohannes commented on composer.json
> +        "massive/search-bundle": "^2.7",
@thomasduenser can you revert that line?

2022-10-28 08:29 UTC, wachterjohannes commented on src/Sulu/Bundle/PageBundle/Search/Metadata/StructureProvider.php
> +                        $component->getName() . '_',
@thomasduenser change to `$componentProperty->getType()`

2022-10-28 08:29 UTC, wachterjohannes commented
@thomasduenser after changed the last comments can you add a screenshot of the result in elasticsearch

2022-10-28 09:12 UTC, alexander-schranz requested changes

2022-10-28 09:12 UTC, alexander-schranz commented on composer.json
> +        "massive/search-bundle": "^2.7",
```suggestion
        "massive/search-bundle": "^2.0",
```

2022-10-28 09:12 UTC, alexander-schranz commented on src/Sulu/Bundle/PageBundle/Search/Metadata/StructureProvider.php
> +                        $component->getName() . '_',
```suggestion
                        $componentProperty->getType() . '_',
```

2022-10-28 11:07 UTC, merged