Adding admin resource URLs to FOSJsRouter automatically
sulu/sulu pull request #6893
Opened 2022-11-04 12:59 UTC by naitsirch

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | -
| Related issues/PRs | #6886
| License | MIT
| Documentation PR | -

#### What's in this PR?

A new compiler pass collects all configured routes for admin resources and adds them to the argument of the `ExposedRoutesExtractor` service of the FOSJsRouterBundle. This way it is not required to follow a naming convention for those routes or add them to the bundle's config manually anymore.

#### Why?

Improve developer experience.

#### Example Usage

irrelevant

#### To Do

- nothing

2022-11-07 17:01 UTC, alexander-schranz requested changes
Thx for working on this. Addded some small comments. Please also rebase your branch via:

```
git remote add sulu git@github.com:sulu/sulu.git
git fetch sulu
git rebase -i sulu/2.6
```

So your branch does also include the last changes of the 2.6 branch which includes a regression test for this endpoint (#6895).

2022-11-07 17:01 UTC, alexander-schranz commented on src/Sulu/Bundle/AdminBundle/SuluAdminBundle.php
> +            $container->addCompilerPass(new ExposeResourceRoutesPass($this->getContainerExtension()->getAlias()));
There is no need to give the alias `$this->getContainerExtension()->getAlias()` into it. It just make the compilerpass code more complex. There is no support to overwrite the alias and so we can avoid this whole check for extension and alias and make the code more readable and easier to maintain.

```suggestion
            $container->addCompilerPass(new ExposeResourceRoutesPass();
```

2022-11-07 17:01 UTC, alexander-schranz commented on src/Sulu/Bundle/AdminBundle/DependencyInjection/Compiler/ExposeResourceRoutesPass.php
> +        $resources = $container->getParameter($this->extensionAlias . '.resources');
As beneath no need to use a variable here as it is defined and will not be changed. Make things more readable.

```suggestion
    public function process(ContainerBuilder $container): void
    {
        $resources = $container->getParameter('sulu_admin.resources');
```

2022-11-07 17:01 UTC, alexander-schranz commented on src/Sulu/Bundle/AdminBundle/DependencyInjection/Compiler/ExposeResourceRoutesPass.php
> +        $extractorDef->replaceArgument(1, $allRouteNames);
We never use abbreviations.

```suggestion
        $extractorDefinition = $container->getDefinition('fos_js_routing.extractor');
        $allRouteNames = array_unique(array_merge($extractorDefinition->getArgument(1), $routeNames));

        $extractorDefinition->replaceArgument(1, $allRouteNames);
```

2022-11-07 17:01 UTC, alexander-schranz commented on src/Sulu/Bundle/AdminBundle/DependencyInjection/Compiler/ExposeResourceRoutesPass.php
> +class ExposeResourceRoutesPass implements CompilerPassInterface
This class is not part of a public sulu API and should so be `@internal` and `@final`.

```suggestion
/**
 * This compiler pass is responsible for adding all configured admin resource
 * routes to `fos_js_routing.routes_to_expose` extension config automatically.
 *
 * @final
 * @internal
 */
class ExposeResourceRoutesPass implements CompilerPassInterface
```

2022-11-09 13:08 UTC, naitsirch commented on src/Sulu/Bundle/AdminBundle/SuluAdminBundle.php
> +            $container->addCompilerPass(new ExposeResourceRoutesPass($this->getContainerExtension()->getAlias()));
The reason I have used the alias for it was, that it is also used in your extension class (see [here](https://github.com/sulu/sulu/blob/916d539fe099126d544f121b19d1fa04faafda24/src/Sulu/Bundle/AdminBundle/DependencyInjection/SuluAdminExtension.php#L146)). But I am fine with changing it to a static string.

2022-11-09 13:13 UTC, alexander-schranz commented on src/Sulu/Bundle/AdminBundle/SuluAdminBundle.php
> +            $container->addCompilerPass(new ExposeResourceRoutesPass($this->getContainerExtension()->getAlias()));
I would not do that for new code. We should tackle that in `3.0` to remove also from the Extension class the `getAlias()` call.

2022-11-09 13:35 UTC, naitsirch commented
@alexander-schranz Thank you for your improvements. I have included all of them and squashed all commits into one.

2022-11-09 14:31 UTC, alexander-schranz commented on src/Sulu/Bundle/AdminBundle/DependencyInjection/Compiler/ExposeResourceRoutesPass.php
> +            }
Looks like some tests are failing because routes is not always available.

```suggestion
            if (isset($resource['routes'])) {
                foreach ($resource['routes'] as $routeName) {
                    $routeNames[] = $routeName;
                }
            }
```

2022-11-11 07:39 UTC, naitsirch commented
With the added line `if (isset($resource['routes'])) {` in the `ExposeResourceRoutesPass` phpstan complains
```
------ --------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   src/Sulu/Bundle/AdminBundle/DependencyInjection/Compiler/ExposeResourceRoutesPass.php                                                                                
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  35     Offset 'routes' on array{routes: array{list: string, detail: string}, security_context: string, security_class: string}|array{routes: array{list?: string, detail?:  
         string}&non-empty-array} in isset() always exists and is not nullable.   
```

The defined config tree in the Configuration class should make sure that the key `routes` is set. But in the unit tests this line fails. I'll look into that.

2022-11-11 13:17 UTC, naitsirch commented
I did not find a way to make the configuration class validate that or set a default value. So I have just added a `@phpstan-ignore-line`. I hope that's fine.

2022-11-11 13:29 UTC, alexander-schranz commented
@naitsirch is fine for me

2022-11-14 12:58 UTC, naitsirch commented
@alexander-schranz Is there any task left for me, before this PR can be merged?

2022-11-15 00:21 UTC, merged

2022-11-15 00:22 UTC, alexander-schranz commented
@naitsirch nothing required. The CI error was unrelated to the PR! thx for this great improvement 👍