Using constructor property promotion for better types
sulu/sulu pull request #7054
Opened 2023-04-03 16:10 UTC by mamazu

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| License | MIT

#### What's in this PR?

Using constructor property promotion for exceptions and fixing the type issues.

#### Why?

* Less Code duplication
    * Types only need to be defined once
    * Less code for assigning properties

#### Example Usage

Before:
```php
/** @var string */
private $test;

/** @param string $test */
public function __construct($test) {
    $this->test = $test;
}
```

After:
```php
/** @param string $test */
public function __construct(private $test) {
}
```

2023-04-03 17:06 UTC, alexander-schranz requested changes

2023-04-03 17:06 UTC, alexander-schranz commented on src/Sulu/Component/Rest/Exception/ConstraintViolationException.php
> +        protected $code
```suggestion
       $code
```

Code should just given to the parent

2023-04-03 17:07 UTC, alexander-schranz commented on src/Sulu/Component/Rest/Exception/ConstraintViolationException.php
> +            $this->code
```suggestion
            $code
```

2023-04-03 17:07 UTC, alexander-schranz approved these changes

2023-04-03 17:09 UTC, alexander-schranz commented on src/Sulu/Bundle/MarkupBundle/Tag/TagNotFoundException.php
>       * @param int $type
@mamazu not sure but I think this should be `string`: https://github.com/sulu/sulu/blob/08a40b7de9c1b3f9a6c42edc928ee8e4ff9ea97c/src/Sulu/Bundle/MarkupBundle/Tag/TagRegistryInterface.php#L23

2023-04-03 17:19 UTC, alexander-schranz commented on src/Sulu/Bundle/MarkupBundle/Tag/TagNotFoundException.php
>       * @param int $type
```suggestion
     * @param string $type
```

2023-04-03 17:19 UTC, alexander-schranz commented on src/Sulu/Bundle/MarkupBundle/Tag/TagNotFoundException.php
> +     * @return int
```suggestion
     * @return string
```

2023-04-03 22:06 UTC, mamazu commented
Your changes all make sense. I'd say go ahead and merge it if there isn't anything else wrong.

2023-04-28 17:53 UTC, mamazu commented
@alexander-schranz Can you have a look at this again? I have updated the branch and now it only fails in the same places the 2.5 Branch also fails.

2023-06-26 14:03 UTC, alexander-schranz requested changes

2023-06-26 14:03 UTC, alexander-schranz commented on src/Sulu/Component/Content/Exception/UnexpectedPropertyType.php
> +    public function getProperty(): PropertyInterface
For BC need to stay as PHPDoc as this method and this class is not final

2023-06-26 14:03 UTC, alexander-schranz commented on src/Sulu/Component/Content/Exception/UnexpectedPropertyType.php
> +    public function getContentType(): ContentTypeInterface
For BC need to stay as PHPDoc as this method and this class is not final

2023-06-26 17:47 UTC, mamazu commented
Yes you are correct. I have removed them.

2023-06-26 17:52 UTC, alexander-schranz approved these changes

2023-06-27 08:05 UTC, merged

2023-06-27 08:05 UTC, alexander-schranz commented
@mamazu thank you!