Allow configuring fos_http_cache tagging without enabled proxy_client for better DX
sulu/sulu pull request #7125
Opened 2023-07-28 14:13 UTC by vntw

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no 
| BC breaks? | no 
| Deprecations? | no  
| Fixed tickets | fixes # 
| Related issues/PRs | # 
| License | MIT
| Documentation PR | sulu/sulu-docs# 

#### What's in this PR?

Right now, to use http cache tagging and its features (especially **twig functions like `fos_httpcache_tag`**) in all environments, you need to have an enabled `proxy_client`. If you're in a different env that has no `proxy_client` enabled, **these functions will be missing** and need to be "polyfilled" in some way, in order not to throw an error, which seems unnecessary.

Looking at the [docs](https://foshttpcachebundle.readthedocs.io/en/latest/features/tagging.html#basic-configuration), I don't immediately see a reason why this shouldn't be possible?

Tested in a 2.5 project without issues but happy to hear your input :)

#### Why?

For better DX

#### Example Usage

No changes to the config

#### To Do

Nothing

2023-08-03 14:19 UTC, alexander-schranz commented
I'm not sure why this check was added. /cc @wachterjohannes do you know?

2023-08-03 14:29 UTC, wachterjohannes requested changes

2023-08-03 14:29 UTC, wachterjohannes commented on src/Sulu/Bundle/HttpCacheBundle/DependencyInjection/SuluHttpCacheExtension.php
> +        $fosHttpCacheConfig['tags']['enabled'] = $config['tags']['enabled'];
@vntw at the end it makes sense to have that - but the tests failing ... seems also to be checked in the foshttpcachebundle

2023-08-03 14:32 UTC, vntw commented on src/Sulu/Bundle/HttpCacheBundle/DependencyInjection/SuluHttpCacheExtension.php
> +        $fosHttpCacheConfig['tags']['enabled'] = $config['tags']['enabled'];
Oh sorry didn't see them, that's weird as it worked for me, I'll take a look and get back to you! Thanks for the reviews

2023-08-03 15:30 UTC, alexander-schranz commented
Looks like we are seeing the problem in the tests:

```bash
Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: You need to configure a proxy_client to get the cache_manager needed for tag handling.
```

2023-08-07 09:43 UTC, vntw commented
@wachterjohannes @alexander-schranz thanks for the review, I took a deeper look and found (in my opinion) a much better and probably the intended solution: the [`noop` proxy client](https://foshttpcachebundle.readthedocs.io/en/latest/reference/configuration/proxy-client.html?highlight=noop#noop). I updated the PR description and code, so now the sulu http cache bundle supports configuring this. I tested this with the following config in dev and prod:

```yaml
sulu_http_cache:
    proxy_client:
        noop: ~

when@prod: &prod
    sulu_http_cache:
        proxy_client:
            symfony:
                enabled: true

when@stage: *prod
```

If the you and the tests are happy, I'll be happy to submit a docs PR to make a little note of it

2023-08-07 10:18 UTC, alexander-schranz commented
@vntw can you rebase this PR to 2.6 as adding configuration options this is kind of a feature and so should be part of 2.6. Also it seems like adoption of the `skeleton` is required so the new noop is used in case of `dev` and `test` env.

In this case I want also check this change with @dbu if this make sense to be used this way.

2023-08-07 10:25 UTC, vntw commented
Rebase done although this _should_ still be BC compatible IMO (but I'm not familiar with the sulu release process)

>What I'm not sure if we need todo noop: false in case the other proxy clients are activated?

Since we don't add any configuration that the user didn't do themselves in this regard, I don't think there's anything to do? If the config is invalid, fos http cache bundle should be the one to complain IMO (as it did with my previous change when the proxy_client was missing)

2023-08-07 10:47 UTC, dbu commented
seems reasonable to me. that  was the main intention of the noop client.

> What I'm not sure if we need todo `noop: false` in case the other proxy clients are activated?

i am not entirely sure but i would have thought the configuration overwrites the other proxy_client. to verify: what happens if you set more than 1 client at the same time? i'd expect that to give an error.

2024-04-29 16:20 UTC, alexander-schranz commented
In general it looks good from my side the only thing we need to check what happens if we now have multiple clients enabled should we set noop to false if other clients are enabled by default. See comment by @dbu https://github.com/sulu/sulu/pull/7125#issuecomment-1667627326  

I rebased to check what the current CI state is.

2024-05-02 12:38 UTC, merged

2024-05-02 12:38 UTC, alexander-schranz commented
@vntw Thank you!