Sort snippet areas in admin frontend by title instead of key
sulu/sulu pull request #7204
Opened 2023-11-17 14:16 UTC by stollr

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | in a way, but only very low break
| Deprecations? | no
| Fixed tickets | -
| Related issues/PRs | -
| License | MIT
| Documentation PR | -

#### What's in this PR?
Changed the sorting of the snippet areas. They are sorted by title instead of their key (which is not visible in the frontend).

#### Why?

Currently the snippet areas are sorted by their key. But this makes it harder to scan the list for the user because titles may have the wrong order.

#### Note

I am using PHP's `Collate` class for comparing the string. But this is only available if the intl extension is loaded. So I have added a fallback to simple `strcmp` function, because the intl extension is not a requirement by Sulu. 
But I am unsure how to handle this in the unit tests. Is it okay how it is done?

2024-04-29 16:25 UTC, alexander-schranz commented
I like the idea. What I think we need to test here if the template uses `translation-keys` if that is correctly handled already.

As Sulu will always support 2 ways of define a title:

Have every meta inlined this way:

```
    <meta>
        <title lang="en">Example</title>
        <title lang="de">Beispiel</title>
    </meta>
```

or using a translation key:

```
    <meta>
        <title>app.example</title>
    </meta>
```

I think the second one sadly is not everywhere correctly target in the snippet area. See https://github.com/sulu/sulu/pull/7188. Maybe @mamazu can have a look if this would break his pull request or if we fine to go with it.

2024-04-29 16:41 UTC, mamazu commented
Well, in the current version of Sulu using translations for the snippet areas is not supported. However if you merge my PR this PR would still work as the sorting happens in the controller and the translations are resolved in a compiler pass. So feel free to merge this.

2024-05-02 10:29 UTC, alexander-schranz requested changes

2024-05-02 10:29 UTC, alexander-schranz commented on src/Sulu/Component/Util/SortUtils.php
> +        \usort($array, function(mixed $itemA, mixed $itemB) use ($collator, $getComparableValue) {
I think the util function should keep the index:

```suggestion
        \uasort($array, function(mixed $itemA, mixed $itemB) use ($collator, $getComparableValue) {
```

2024-05-02 10:29 UTC, alexander-schranz commented on src/Sulu/Bundle/SnippetBundle/Controller/SnippetAreaController.php
> +                'areas' => $dataList,
As the util function keep the index we should reintroduce the array_values part:

```suggestion
                'areas' => \array_values($dataList),
```

2024-05-02 10:31 UTC, alexander-schranz approved these changes

2024-05-02 12:18 UTC, merged