Bugfix/add pagination to admin search
sulu/sulu pull request #7228
Opened 2023-12-06 00:54 UTC by zanturik

| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no 
| BC breaks? | no 
| Deprecations? | no 
| Fixed tickets | fixes #7109
| Related issues/PRs | #7109
| License | MIT
| Documentation PR |

#### What's in this PR?

Add pagination to admin search page

#### Why?

Because good search pages contains pagination.

#### Example Usage

Search * in admin search page. Play with pagination.

#### To Do

2024-03-18 11:28 UTC, alexander-schranz commented
@zanturik Thx for working on this and sorry for the late response.

I did give this a quick try but it looks like this isn't working. Maybe related to the removed zend lucene part or fasl? But it even not triggers a request so maybe related more to the JS part.

![search](https://github.com/sulu/sulu/assets/1698337/3080c8f9-10a1-4a0a-9c90-669082012b2e)

The pagination component itself is maybe a little bit small on small screens. So maybe we should make that atleast the same width as the search field.

2024-03-18 14:54 UTC, zanturik commented
> @zanturik Thx for working on this and sorry for the late response.
> 
> I did give this a quick try but it looks like this isn't working. Maybe related to the removed zend lucene part or fasl? But it even not triggers a request so maybe related more to the JS part.
You are right, my bad, one line was not pushed. Fixed, Please test again.

> The pagination component itself is maybe a little bit small on small screens. So maybe we should make that atleast the same width as the search field.
I agree. The problem it that it's a Pagination component displaying results/pagination this way, I'm just reusing it. The problem itself comes from "max-width" of .search-result class. I think it should be fixed in a separate task, since it's not the only place where search is used and design in other places may differ.

2024-04-18 14:17 UTC, alexander-schranz requested changes
I checked this with the Team and the only required change is that the `Pagination` component should go over the same width as the search field itself. Can you tackle that?

2024-04-18 16:37 UTC, zanturik commented
> I checked this with the Team and the only required change is that the `Pagination` component should go over the same width as the search field itself. Can you tackle that?

fixed, please review.

2024-04-29 16:59 UTC, alexander-schranz approved these changes

2024-04-29 17:00 UTC, alexander-schranz commented
@zanturik Looks good for me, Thanks you for the contribution! Auto merged when the CI finished.

2024-04-29 17:16 UTC, merged