Tests should crash on non zero exit code
sulu/sulu pull request #7342
Opened 2024-04-03 09:33 UTC by mamazu

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | -
| Related issues/PRs | #6834
| License | MIT
| Documentation PR | -

#### What's in this PR?
This adds the function that the tests crash when one of the steps exists with a non-zero exit code.

#### Why?
Currently the tests just ignore the exit code and continue running which then causes issues further down the suite. This should make the tests easier to debug as the errors are reported earlier and closer to the source.

2024-04-03 15:17 UTC, alexander-schranz commented
> Currently the tests just ignore the exit code and continue running which then causes issues further down the suite.

This is the expected behaviour of the runtests script. We run always all scripts and not exit directly when there is an error in one of the scripts.

2024-04-03 15:20 UTC, mamazu commented
Okay the problem I was encountering in this case is the test shouldn't run if the init step fails (see the jackalope 2 merge request).

2024-04-03 15:23 UTC, mamazu commented
And the test cases in this case aren't affected because they are allowed to fail, their failure is recorded and just passed on.

2024-04-03 15:35 UTC, alexander-schranz commented
I see I would update the `init_dbal` part to throw exception there if the process for schema update finish with a none zero exit code.

2024-04-03 15:36 UTC, alexander-schranz commented
Something like:

```php
    $process = exec_sf_cmd(
        'doctrine:schema:update --force'
    );
    
    if (0 !== $process->getExitCode()) {
        // error already outputted before via write_error

        exit($process->getExitCode());
    }
```

2024-04-03 15:48 UTC, mamazu commented
That's also acceptable.

2024-04-03 15:50 UTC, alexander-schranz commented
We should target the 2.4 for this change.

2024-04-03 15:52 UTC, mamazu commented
Changed the base.

2024-04-03 16:51 UTC, alexander-schranz commented on bin/runtests
> +        exit($process->getExitCode());
we should not exit when one bundle fails to init.

2024-04-03 16:52 UTC, alexander-schranz commented on bin/runtests
> -        ' sulu:document:initialize --purge --force --ansi'
I think we don't need to catch this. Aslong as the tests run as expected it is not required that a bundle uses the document manager bundle.

2024-04-03 21:10 UTC, mamazu commented
I wanted to catch this: https://github.com/sulu/sulu/actions/runs/8525431456/job/23352362111?pr=6834

In this the Init Task is successful although the update of the schema failed. Without this none of the tests will work.

2024-04-10 09:35 UTC, alexander-schranz requested changes

2024-04-10 09:35 UTC, alexander-schranz commented on bin/runtests
> +    }
```suggestion
```

2024-04-10 09:35 UTC, alexander-schranz commented on bin/runtests
> +    }
```suggestion
```

2024-04-10 09:35 UTC, alexander-schranz commented
That error would still be catched we just don't should exit on the `init_bundle` part.

2024-04-10 09:44 UTC, mamazu commented
Looks good can you apply those and merge because the app doesn't support that.

2024-04-10 10:01 UTC, alexander-schranz approved these changes

2024-04-10 10:16 UTC, merged