Migrate rest routings to default symfony routing files of TagBundle
sulu/sulu pull request #7511
Opened 2024-07-07 11:09 UTC by TheCadien

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no 
| Fixed tickets | fixes # [7434>](https://github.com/sulu/sulu/issues/7434)
| Related issues/PRs | # [7434>](https://github.com/sulu/sulu/issues/7434)
| License | MIT
| Documentation PR | sulu/sulu-docs# 

#### What's in this PR?
See ticket # [7434>](https://github.com/sulu/sulu/issues/7434)

2025-05-22 22:34 UTC, mamazu requested changes
Some minor things.

2025-05-22 22:34 UTC, mamazu commented on src/Sulu/Bundle/TagBundle/Resources/config/routing_api.yaml
> +    format: json
I don't know what this `format` key is supposed to do. If you want to specify what values it can have it should be something like
```
sulu_tag.get_tag:
    requirements: { _format: json|csv }
```

2025-05-22 22:34 UTC, mamazu commented on src/Sulu/Bundle/TagBundle/Resources/config/routing_api.yaml
> +    controller: sulu_tag.tag_controller::patchAction
```suggestion
    controller: sulu_tag.tag_controller::cpatchAction
```

2025-06-07 15:47 UTC, alexander-schranz commented on src/Sulu/Bundle/TagBundle/Resources/config/routing_api.yaml
> +    format: json
format does the same as options: _format so its obsolete if already defined in options

2025-06-07 15:51 UTC, alexander-schranz commented on src/Sulu/Bundle/TagBundle/Resources/config/routing_api.yaml
> +       _format: json|csv
this was missing as it was currently handled by `type: rest` but that should be removed.

2025-06-07 16:06 UTC, merged