Custom urls without phpcr
sulu/sulu pull request #7570
Opened 2024-08-23 09:22 UTC by mamazu

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | closes #7566 
| Related issues/PRs | -
| License | MIT
| Documentation PR | -

#### What's in this PR?
Replacing the custom url implementation of phpcr with some doctrine entities.

#### Why?
phpcr should be removed in the next major version and we can really simplify the logic here.

2024-09-06 16:03 UTC, mamazu commented on src/Sulu/Bundle/CustomUrlBundle/Controller/CustomUrlHistoryController.php
> +            $this->entityManager->remove($entity);
Trigger CustomUrlRemoved event.

2024-09-06 16:03 UTC, mamazu commented on src/Sulu/Bundle/CustomUrlBundle/Resources/config/routing.xml
>          </service>
For some reason the domain default collection is always the fourth argument. This looks weird.

2024-09-06 17:17 UTC, mamazu commented on src/Sulu/Component/CustomUrl/Repository/RowsIterator.php
> +class RowsIterator extends \ArrayIterator
This should probably be a serializer extension for this entity.

2024-09-06 17:19 UTC, mamazu commented on src/Sulu/Component/CustomUrl/Routing/CustomUrlDefaultsProvider.php
> +
This should be the same logic as it was before with the `ExternalLink` and `InternalLink` from the Enhancers directory.

2024-09-29 21:14 UTC, mamazu commented on config/webspaces/sulu-blog.xml
> +                    </custom-urls>
Remove before merging.

2025-02-20 12:08 UTC, alexander-schranz commented on src/Sulu/Component/CustomUrl/Manager/CustomUrlManager.php
>  class CustomUrlManager implements CustomUrlManagerInterface
We want to get ride of the managers for the bundles which we rewrite.

If you want and have time you can put the whole bundle into the `packages/custom-url` directory and follow the message / message handler pattern:

```php
new CreateCustomUrlMessage($data);
new ModifyCustomUrlMessage($id, $data);
new RemoveCustomUrlMessage($id);
```

See https://github.com/sulu/sulu/tree/3.0/packages/snippet/src/Application/Message

see the architecture and directory structure here Domain the entitiy, exception, events, repository interface live, infrastructure the doctrine implementation but also all third party integration sulu admin, symfony event ...., userinterface the admin controller and application the message and message handlers:

https://github.com/sulu/sulu/tree/3.0/packages/snippet/src

let me know if you want to tackle that.

2025-02-20 12:13 UTC, mamazu commented on src/Sulu/Component/CustomUrl/Manager/CustomUrlManager.php
>  class CustomUrlManager implements CustomUrlManagerInterface
I can do that and I'll get back to you if I have questions.

2025-02-20 12:13 UTC, mamazu commented on src/Sulu/Component/CustomUrl/Manager/CustomUrlManager.php
>  class CustomUrlManager implements CustomUrlManagerInterface
However, I also thought about this topic again and think that a completely different approach would be better for custom urls here.

2025-02-20 15:04 UTC, alexander-schranz commented on packages/custom-url/src/Domain/Model/CustomUrlRoute.php
Just as it did come up in some discussion last week. I was not longer sure.

We require a CustomUrlRoute entity because custom Urls also have a route history? Or what was it that we decided to use an own route model?

2025-02-20 15:16 UTC, mamazu commented on packages/custom-url/src/Domain/Model/CustomUrlRoute.php
Correct. We could also rename it to CustomUrlHistory but essentially all routes in the history are active because if we change the route it still matches all routes and forwards them to the new page.

2025-02-20 15:25 UTC, alexander-schranz commented on packages/custom-url/src/Domain/Model/CustomUrlRoute.php
Thx I think Route make sense then.

2025-02-21 09:42 UTC, mamazu commented
We're going to reimplement with a custom Symfony CMF Router.

2025-02-28 12:29 UTC, alexander-schranz commented on composer.json
> +        "symplify/config-transformer": "^12.4"
unexpected dependency

2025-03-13 17:53 UTC, mamazu commented on packages/custom-url/config/doctrine/CustomUrl.orm.xml
> +        <id name="id" type="string" column="id">
We can't use anything else otherwise the Admin UI will bug out.

2025-03-13 17:54 UTC, mamazu commented on src/Sulu/Bundle/PageBundle/EventListener/WebspaceSerializeEventSubscriber.php
> +        return;
Custom urls will no longer be part of the webspace serializer output

2025-03-14 15:23 UTC, mamazu commented on src/Sulu/Bundle/PageBundle/EventListener/WebspaceSerializeEventSubscriber.php
> +        return;
They will still return urls but only the urls of the portal and no longer the list of all custom urls.

2025-03-15 15:54 UTC, mamazu commented on packages/custom-url/config/lists/custom_urls.xml
> +        </property>
We don't want to filter for it in the UI only in the code, maybe there is a way?

2025-03-15 15:54 UTC, mamazu commented on packages/custom-url/src/Infrastructure/Sulu/EventSubscriber/CacheInvalidationSubscriber.php
> +class CacheInvalidationSubscriber implements EventSubscriberInterface
This probably has to be split into subscriber for document updates and subscriber for customurl entity updates.

2025-03-21 09:38 UTC, alexander-schranz commented on src/Sulu/Bundle/PageBundle/EventListener/WebspaceSerializeEventSubscriber.php
> +        return;
@chirimoya lets discuss this it seems like a strange implementation that every custom URL is always load when Admin is loaded to list it here:

![Bildschirmfoto 2025-03-21 um 10 37 04](https://github.com/user-attachments/assets/7eb2c368-cb99-4ba7-b524-f3975997b945)

2025-03-21 09:42 UTC, mamazu commented on packages/custom-url/config/lists/custom_urls.xml
> +        </property>
I'm stupid. Fixed

2025-04-08 13:21 UTC, mamazu commented
We also still need to check where to put the validation (like does this domain part list belong to the webspace you're configuring, are all request parameters set etc.)

2025-05-22 08:48 UTC, alexander-schranz requested changes
did just check the directory structure, deeper review of the implementation of the custom urls into the admin will be done by @wachterjohannes

2025-05-22 08:48 UTC, alexander-schranz commented on packages/custom-url/config/document.php
like in the other bundles I would keep this in the Bundle class, like to have a single class which is responsible for the framework integration and so have all in overview how framework config is given to the services instead of split it up into severl files

2025-05-22 08:48 UTC, alexander-schranz commented on packages/custom-url/config/routing_api.yml
we use `.yaml` for new files

2025-05-22 08:48 UTC, alexander-schranz commented on packages/custom-url/config/symfony.php
same as above not split the service up

2025-05-22 08:48 UTC, alexander-schranz commented on packages/custom-url/config/message_handler.php
same as above not split the service up

2025-05-22 08:48 UTC, alexander-schranz commented on packages/custom-url/src/Infrastructure/Repository/CustomUrlRepository.php
> +namespace Sulu\CustomUrl\Infrastructure\Repository;
```suggestion
namespace Sulu\CustomUrl\Infrastructure\Doctrine\Repository;
```

doctrine namespace missing

2025-05-22 08:48 UTC, alexander-schranz commented on packages/custom-url/src/Infrastructure/Sulu/EventSubscriber/CacheInvalidationSubscriber.php
> +namespace Sulu\CustomUrl\Infrastructure\Sulu\EventSubscriber;
```suggestion
namespace Sulu\CustomUrl\Infrastructure\Sulu\HttpCache;
```

there is no event subscriber bundle this is connection point to the http cache bundle

2025-05-22 08:48 UTC, alexander-schranz commented on packages/custom-url/src/Infrastructure/Symfony/Normalizer/CustomUrlNormalizer.php
> +namespace Sulu\CustomUrl\Infrastructure\Symfony\Normalizer;
```suggestion
namespace Sulu\CustomUrl\Infrastructure\Symfony\Serializer;
```

this is connection point to symfony/serializer package

2025-05-22 08:48 UTC, alexander-schranz commented on packages/custom-url/src/Infrastructure/Symfony/Router/CustomUrlRouter.php
> +class CustomUrlRouter implements RouterInterface
this will be refactored to our new routing providers. currently  out of scope until we removed all old routing parts

2025-05-22 08:48 UTC, alexander-schranz commented on packages/custom-url/src/Resources/js/components/CustomUrl/CustomUrl.js
the whole src/Resources/js should be removed the new JS is already here:

https://github.com/sulu/sulu/tree/3.0/packages/custom-url/assets/js

2025-05-27 08:21 UTC, wachterjohannes requested changes

2025-05-27 08:21 UTC, wachterjohannes commented on packages/custom-url/config/doctrine/CustomUrl/CustomUrl.orm.xml
> +        <field name="created" type="datetime" />
this should be added automatically thru the MappingSubscriber of the AuditableInterface

2025-05-27 08:21 UTC, wachterjohannes commented on packages/custom-url/config/doctrine/CustomUrl/CustomUrl.orm.xml
> +        <field name="created" type="datetime" />
created/changed/creator/changer

2025-05-27 08:21 UTC, wachterjohannes commented on packages/custom-url/config/document.php
document.php? why not services.php?

2025-05-27 08:21 UTC, wachterjohannes commented on packages/custom-url/config/routing_api.yml
keep the format and the definition as close as possible to the other packages. See article route definition:

```
sulu_article.get_articles:
    path: /articles.{_format}
    methods: GET
    controller: sulu_article.admin_article_controller::cgetAction
    format: json

sulu_article.get_article:
    path: /articles/{id}.{_format}
    methods: GET
    controller: sulu_article.admin_article_controller::getAction
    format: json
```

2025-05-27 08:21 UTC, wachterjohannes commented on packages/custom-url/src/Application/MessageHandler/CreateCustomUrlMessageHandler.php
> +        private readonly CustomUrlMapperInterface $mapper,
in other classes we have the possibility to have multiple mappers (see CreateArticleMessageHandler)

2025-05-27 08:21 UTC, wachterjohannes commented on packages/custom-url/src/Application/MessageHandler/ModifyCustomUrlMessageHandler.php
> +        private readonly CustomUrlMapperInterface $mapper,
Same here

2025-05-27 08:21 UTC, wachterjohannes commented on packages/custom-url/src/Application/MessageHandler/ModifyCustomUrlMessageHandler.php
> +        if ($customUrl->getWebspace() !== $message->getWebspaceKey()) {
i think we can omit this check if we remove the `getWebspaceKey` from the `ModifyCustomUrlMessage`.

2025-05-27 08:21 UTC, wachterjohannes commented on packages/custom-url/src/Application/MessageHandler/RemoveCustomUrlMessageHandler.php
> +        if ($customUrl->getWebspace() !== $message->getWebspaceKey()) {
same here

2025-05-27 08:21 UTC, wachterjohannes commented on packages/custom-url/src/Application/Messages/ModifyCustomUrlMessage.php
> +        private string $webspaceKey,
remove as this does not make any sense to change it

2025-05-27 08:21 UTC, wachterjohannes commented on packages/custom-url/src/Application/Messages/RemoveCustomUrlMessage.php
> +        private string $webspaceKey
remove as this does not make any sense to change it

2025-05-27 08:21 UTC, wachterjohannes commented on packages/custom-url/src/Infrastructure/Doctrine/Repository/CustomUrlRepositoryInterface.php
> +interface CustomUrlRepositoryInterface extends ServiceEntityRepositoryInterface, ObjectRepository
repository interfaces should be in Domain\Repository (see page package)

2025-05-27 08:21 UTC, wachterjohannes commented on packages/custom-url/src/Infrastructure/Doctrine/Repository/CustomUrlRepository.php
> +    public function findNewestPublishedByUrl(string $url, ?string $locale = null): ?CustomUrlInterface
we should refactor this to be the same interface as PageRepositoryInterface: `createNew`, `add`, `remove`, `findOneBy`, `findBy`, ... So that we have the same interface in every package

2025-05-27 08:21 UTC, wachterjohannes commented on packages/custom-url/src/Infrastructure/Doctrine/Repository/CustomUrlRouteRepository.php
> +    public function findByCustomUrl(CustomUrlInterface $customUrl): array
change also here the interface to make it comparable to page package

2025-05-27 08:21 UTC, wachterjohannes commented on packages/custom-url/src/Infrastructure/Doctrine/Repository/CustomUrlRouteRepositoryInterface.php
> +interface CustomUrlRouteRepositoryInterface
repository interfaces should be in Domain\Repository (see page package)

2025-05-27 08:21 UTC, wachterjohannes commented on packages/custom-url/src/Infrastructure/Sulu/Admin/CustomUrlAdmin.php
> +    private function getSecurityContextPermissions(): array
make this also static as `getCustomUrlSecurityContext `

2025-05-27 08:21 UTC, wachterjohannes commented on packages/custom-url/src/Infrastructure/Sulu/HttpCache/CacheInvalidationSubscriber.php
> +class CacheInvalidationSubscriber implements EventSubscriberInterface
@alexander-schranz or @Prokyonn why dont we have such class in the page-package? Is that in the content-package already implmented?

2025-05-27 08:21 UTC, wachterjohannes commented on packages/custom-url/src/Infrastructure/Sulu/Trash/CustomUrlTrashItemHandler.php
> + * title: string,
fix indentation

2025-05-27 08:21 UTC, wachterjohannes commented on packages/custom-url/src/Infrastructure/Symfony/Fixtures/LoadCustomUrlFixture.php
where is that used? shouldnt we move this in the tests folder? or even remove it as we should not run that in production

2025-05-27 08:21 UTC, wachterjohannes commented on packages/custom-url/src/Infrastructure/Symfony/Router/CustomUrlRouter.php
> +class CustomUrlRouter implements RouterInterface
@alexander-schranz should we then also remove this?

2025-05-27 08:21 UTC, wachterjohannes commented on packages/custom-url/src/Infrastructure/Symfony/Serializer/CustomUrlNormalizer.php
> +        $context[AbstractNormalizer::IGNORED_ATTRIBUTES][] = 'created';
@alexander-schranz sould we move this to the auditable thing i build in this PR? https://github.com/sulu/sulu/pull/7972

2025-05-27 08:21 UTC, wachterjohannes commented on packages/custom-url/tests/Application/bin/console.php
> +declare(strict_types=1);
remove all this declerations from all files

2025-05-27 08:21 UTC, wachterjohannes commented on packages/custom-url/tests/Application/config/webspaces/sulu.io.xml
> +                        <url language="en">{host}/en</url>
didnt you need a custom-url definition to have functional testcases?

2025-05-27 19:11 UTC, mamazu commented on packages/custom-url/config/doctrine/CustomUrl/CustomUrl.orm.xml
> +        <field name="created" type="datetime" />
Yes forgot to implement the interface. 🤦

2025-05-27 19:22 UTC, mamazu commented on packages/custom-url/src/Application/MessageHandler/CreateCustomUrlMessageHandler.php
> +        private readonly CustomUrlMapperInterface $mapper,
Well technically you can also do that here with a composite mapper. But I can also change it to an iterable.

2025-05-27 19:51 UTC, mamazu commented on packages/custom-url/config/routing_api.yml
Fixed.

2025-05-27 20:17 UTC, mamazu commented on packages/custom-url/src/Infrastructure/Symfony/Fixtures/LoadCustomUrlFixture.php
We could, this is mostly for testing the admin performance. I don't know if there is a better place to put it.

2025-05-27 20:21 UTC, mamazu commented on packages/custom-url/src/Infrastructure/Symfony/Serializer/CustomUrlNormalizer.php
> +        $context[AbstractNormalizer::IGNORED_ATTRIBUTES][] = 'created';
I don't think that this can be generalized. We only want to show the author and not the changer of the resource in the API.

2025-05-27 20:26 UTC, mamazu commented on packages/custom-url/tests/Application/config/webspaces/sulu.io.xml
> +                        <url language="en">{host}/en</url>
Technically only for rendering the admin form and that's not being tested. We're just testing the API to get and update the entries. But we might also want to check the admin configuration endpoint for the custom urls to check there are no bc breaks there.

2025-06-19 10:52 UTC, mamazu commented on packages/custom-url/src/Infrastructure/Symfony/Router/CustomUrlRouter.php
> +class CustomUrlRouter implements RouterInterface
I already removed the old logic that used the phpcr routing, so if this is being merged then customurl routing will not work anymore.

2025-06-19 10:58 UTC, mamazu commented on packages/custom-url/src/Application/Messages/ModifyCustomUrlMessage.php
> +        private string $webspaceKey,
We don't need it for changing. We need to check if the user has permission to change the custom urls for this webspace. Maybe this could also be handled in the security settings.

2025-06-19 11:08 UTC, mamazu commented on packages/custom-url/src/Domain/Event/CustomUrlCreatedEvent.php
> +class CustomUrlCreatedEvent extends DomainEvent
Maybe we could also introduce a `ResourceEvent` to reduce the amount of code duplication.

2025-06-19 11:22 UTC, mamazu commented on packages/custom-url/src/Infrastructure/Doctrine/Repository/CustomUrlRepository.php
> +    public function findNewestPublishedByUrl(string $url, ?string $locale = null): ?CustomUrlInterface
Would it maybe also make sense to add a "Sulu Repository" interface that has those methods?

2025-06-19 11:56 UTC, mamazu commented on packages/custom-url/src/Infrastructure/Sulu/Trash/CustomUrlTrashSubscriber.php
> +final class CustomUrlTrashSubscriber implements EventSubscriberInterface
This is nothing CustomUrl specific. Maybe this makes sense to move to the trash bundle itself.

2025-06-19 14:17 UTC, mamazu commented
Also, I'm currently copying over request/response JSON from the 2.6 branch to keep the Backwards compatibility and I notice that the endpoint also returns a 200 in case of an error and then just a JSON with the error information:
![image](https://github.com/user-attachments/assets/419c12f1-c7bd-4609-b4eb-7945373e8475)

Do we want to keep that behavior? Or risk a BC break for this?

2025-06-23 05:35 UTC, alexander-schranz commented on packages/custom-url/src/Infrastructure/Symfony/Router/CustomUrlRouter.php
> +class CustomUrlRouter implements RouterInterface
yes router should be removed the website requires a new implementation on our own:  `RouteCollectionForRequestLoaderInterface` by add a new service to the `Infrastructure\Sulu\Route`

2025-06-23 05:37 UTC, alexander-schranz commented
> notice that the endpoint also returns a 200 in case of an error

Sure should be then a `4**` status code to show a proper error messag ein the frontend.

2025-09-18 12:18 UTC, Prokyonn commented on packages/custom-url/src/Infrastructure/Sulu/HttpCache/CacheInvalidationSubscriber.php
> +class CacheInvalidationSubscriber implements EventSubscriberInterface
No, tbh I think this is still missing completely 😅

2025-10-01 12:32 UTC, wachterjohannes commented on packages/custom-url/src/Domain/Repository/CustomUrlRouteRepository.php
> +namespace Sulu\CustomUrl\Domain\Repository;
move to namespace `Sulu\CustomUrl\Infrastructure\Doctrine\Repository`

2025-10-01 13:34 UTC, mamazu commented on packages/custom-url/tests/Unit/Application/MessageHandler/ModifyCustomUrlMessageHandlerTest.php
> +        } $this->entityManager->flush();
We should also clear the entity manager then to not leave any entities laying around. Or move this to the repository.

2025-10-10 07:21 UTC, mamazu commented on packages/custom-url/src/Domain/Model/CustomUrl.php
> +        }
This should be a doctrine query as it currently leaves behind a lot of unused entities.

2025-10-15 08:13 UTC, wachterjohannes commented on packages/custom-url/src/Domain/Model/CustomUrl.php
> +        }
not sure what you mean with that - we only check if the new route is not already part of the current routes.

But nevermind this part will be refactored in the followup PR where i will implement the routing

2025-10-15 13:21 UTC, merged

2025-10-15 13:21 UTC, alexander-schranz commented
Thx @mamazu @wachterjohannes !

2025-10-15 13:41 UTC, mamazu commented on src/Sulu/Bundle/PageBundle/EventListener/WebspaceSerializeEventSubscriber.php
> +        return;
@wachterjohannes Just out of curiosity how was this solved?

2025-10-16 13:01 UTC, alexander-schranz commented
There seems to be some untackled phpstan errors @mamazu @wachterjohannes 

<img width="1242" height="1039" alt="Bildschirmfoto 2025-10-16 um 15 00 54" src="https://github.com/user-attachments/assets/798d4fbb-c5be-4fa1-925d-88928d48fbee" />

2025-10-16 13:25 UTC, mamazu commented
On it.