Add uuid and linkitems to link content type
sulu/sulu pull request #7586
Opened 2024-09-13 01:08 UTC by manuxi

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | yes
| BC breaks? | no
| Deprecations? | no

#### What's in this PR?

Added uuid and linkitems to the view of link content type.

#### Why?

When using the link content type it was not possible to me to get title/contents of the page easily since only the url was provided.

2024-09-13 10:13 UTC, alexander-schranz requested changes
@manuxi thx for the pull request. I know that for your usecase you might want to get the linkItems but that would in most cases an overhead. So instead of returning the link items the view should just give you all information that you can call the resolver yourself via a custom twig extension. So return `href` you require for your usecase. The `provider` should already be given as I see the lines above, so this might enough to get all information you can process then:

2024-09-13 10:13 UTC, alexander-schranz commented on src/Sulu/Component/Content/Types/Link.php
> +
`view` should not resolve anything it should mostly just provide raw informations.

We should inside the `view` just return `href` and `provider` when that is the one you want to load more data and not recalling a resolver here:

```suggestion
        $result['href'] = $value['href'] ?? null;
```

Then it up to the user itself if the want to call something via a twig extension or not.

2024-09-17 09:00 UTC, alexander-schranz commented
@manuxi Can you adjust the Link Content Type Test to test on the new value and run `composer php-cs-fix -- src/Sulu/Component/Content/Types/Link.php" to fix the code style.

2024-09-17 18:34 UTC, manuxi commented on src/Sulu/Component/Content/Types/Link.php
> +        $segmentKey = null
Seems that the cs-fixer added a comma in line 127 after $segementKey = null

2024-09-27 10:11 UTC, merged