fix: using userRepository to allow custom class overrides to work again
sulu/sulu pull request #7609
Opened 2024-10-10 12:57 UTC by Cephra

| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| License | MIT

#### What's in this PR?

I've changed a line in `src/Sulu/Bundle/SecurityBundle/SingleSignOn/Adapter/OpenId/OpenIdSingleSignOnAdapter.php` so it uses the `UserRepository` to create a new Instance of a User.

#### Why?

Without doing that, it'll always be the Sulu User and any custom overrides you may have done will cause an error due to the classes not matching.

#### Example Usage

2024-10-11 11:15 UTC, Cephra commented
@alexander-schranz Hey, turns out I forgot to add the import for UserInterface, sorry about that.

2024-10-11 17:23 UTC, Cephra commented
@alexander-schranz I will change this back to draft as I'm not sure why I get the errors that I'm getting. We are using these fixes already in our sulu stack without any issues. I'll investigate further, update my PR and set it back to ready once I solved the linting issues.

2024-10-31 08:26 UTC, alexander-schranz approved these changes

2024-10-31 08:28 UTC, alexander-schranz commented on src/Sulu/Bundle/SecurityBundle/SingleSignOn/Adapter/OpenId/OpenIdSingleSignOnAdapter.php
> +            $defaultRoleKey = $this->roleRepository->createNew();
this looks wrong as we try to create a `UserRole` via `RoleRepository` which returns a `Role` not a `UserRole` which is wrong. This change I need be reverted:

```suggestion
            $defaultRoleKey = new UserRole();
```

The `UserRole` is not overwriteable and so not require the repository to be created.

2024-10-31 08:31 UTC, alexander-schranz commented on src/Sulu/Bundle/SecurityBundle/Tests/Unit/SingleSignOn/Adapter/OpenId/OpenIdSingleSignOnAdapterTest.php
> +        $this->roleRepository->createNew()->willReturn($role->reveal());
```suggestion
```

2024-10-31 08:31 UTC, alexander-schranz commented on src/Sulu/Bundle/SecurityBundle/Tests/Unit/SingleSignOn/Adapter/OpenId/OpenIdSingleSignOnAdapterTest.php
> +        $this->userRepository->createNew()->willReturn($user->reveal());
There is no need here for such complexity of mockings just return a real user entity here:

```suggestion
        $user = new User();
        $this->userRepository->createNew()->willReturn($user);
```

2024-10-31 08:32 UTC, alexander-schranz requested changes
The UserRole can not be created via RoleRepository so instead it should be directly created.

2024-10-31 08:39 UTC, alexander-schranz requested changes
.

2024-10-31 08:59 UTC, alexander-schranz commented
I can not apply the patches to the your fork so I updated the changes in an own PR here#7633

2024-10-31 08:59 UTC, closed without merging